// Card Type 1 cards
export const cardDataType1 = [
    {'actors': ['Tommy Lee Jones', 'Josh Brolin'], 'character': 'Agent K', 'movies': ['Men in Black 3', 'Men in Black 3'], 'type': 1}, 
    {'actors': ['Jude Law', 'Richard Harris'], 'character': 'Albus Dumbledore', 'movies': ['Fantastic Beasts: The Crimes of Grindelwald', 'Fantastic Beasts: The Secrets of Dumbledore'], 'type': 1}, 
    {'actors': ['Jude Law', 'Michael Gambon'], 'character': 'Albus Dumbledore', 'movies': ['Fantastic Beasts: The Crimes of Grindelwald', 'Fantastic Beasts: The Secrets of Dumbledore'], 'type': 1}, 
    {'actors': ['Richard Harris', 'Michael Gambon'], 'character': 'Albus Dumbledore', 'movies': ["Harry Potter and the Sorcerer's Stone", 'Harry Potter and the Chamber of Secrets'], 'type': 1}, 
    {'actors': ['Hayden Christensen', 'Jake Lloyd'], 'character': 'Anakin Skywalker', 'movies': ['Star Wars: Episode II - Attack of the Clones, Star Wars: Episode III – Revenge of the Sith', 'Star Wars: Episode I - The Phantom Menace'], 'type': 1}, 
    {'actors': ['David Keith', 'Zac Efron'], 'character': 'Andrew McGee', 'movies': ['Firestarter (1984)', 'Firestarter (2022)'], 'type': 1}, 
    {'actors': ['Charlie Sheen', 'Luke Evans'], 'character': 'Aramis', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Jeremy Irons', 'Charlie Sheen'], 'character': 'Aramis', 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['Jeremy Irons', 'Luke Evans'], 'character': 'Aramis', 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['John Malkovich', 'Kiefer Sutherland'], 'character': 'Athos', 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['John Malkovich', 'Matthew Macfadyen'], 'character': 'Athos', 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Kiefer Sutherland', 'Matthew Macfadyen'], 'character': 'Athos', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Dana Barron', 'Dana Hill'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Vacation", "National Lampoon's European Vacation"], 'type': 1}, 
    {'actors': ['Dana Barron', 'Juliette Lewis'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Vacation", "National Lampoon's Christmas Vacation"], 'type': 1}, 
    {'actors': ['Dana Barron', 'Marisol Nichols'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Vacation", "National Lampoon's Vegas Vacation"], 'type': 1}, 
    {'actors': ['Dana Barron', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Dana Hill', 'Juliette Lewis'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's European Vacation", "National Lampoon's Christmas Vacation"], 'type': 1}, 
    {'actors': ['Dana Hill', 'Marisol Nichols'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's European Vacation", "National Lampoon's Vegas Vacation"], 'type': 1}, 
    {'actors': ['Dana Hill', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's European Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Juliette Lewis', 'Marisol Nichols'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Christmas Vacation", "National Lampoon's Vegas Vacation"], 'type': 1}, 
    {'actors': ['Juliette Lewis', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Christmas Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Marisol Nichols', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ["National Lampoon's Vegas Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Jeremy Ray Taylor', 'Jay Ryan'], 'character': 'Ben Hanscom', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['John Ritter', 'Jeremy Ray Taylor'], 'character': 'Ben Hanscom', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['John Ritter', 'Jay Ryan'], 'character': 'Ben Hanscom', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ["Annette O'Toole", 'Sophia Lillis'], 'character': 'Beverly Marsh', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ["Annette O'Toole", 'Jessica Chastain'], 'character': 'Beverly Marsh', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Sophia Lillis', 'Jessica Chastain'], 'character': 'Beverly Marsh', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Martin Freeman', 'Ian Holm'], 'character': 'Bilbo Baggins', 'movies': ['The Hobbit: An Unexpected Journey', 'The Hobbit: The Desolation of Smaug'], 'type': 1}, 
    {'actors': ['Jaeden Martell', 'James McAvoy'], 'character': 'Bill Denbrough', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Richard Thomas', 'Jaeden Martell'], 'character': 'Bill Denbrough', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['Richard Thomas', 'James McAvoy'], 'character': 'Bill Denbrough', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Patrick Swayze', 'Edgar Ramírez'], 'character': 'Bodhi', 'movies': ['Point Break (1991)', 'Point Break (2015)'], 'type': 1}, 
    {'actors': ['Lindsay Lohan', 'Angourie Rice'], 'character': 'Cady Heron', 'movies': ['Mean Girls (2004)', 'Mean Girls (2024)'], 'type': 1}, 
    {'actors': ['Drew Barrymore', 'Ryan Kiera Armstrong'], 'character': 'Charlie McGee', 'movies': ['Firestarter (1984)', 'Firestarter (2022)'], 'type': 1}, 
    {'actors': ['Jodie Foster', 'Julianne Moore'], 'character': 'Clarice Starling', 'movies': ['Silence of the Lambs', 'Hannibal'], 'type': 1}, 
    {'actors': ['Jason Momoa', 'Arnold Schwarzenegger'], 'character': 'Conan', 'movies': ['Conan the Barbarian (2011)', 'Conan the Barbarian (1982)'], 'type': 1}, 
    {'actors': ['Donald Sutherland', 'Tom Blyth'], 'character': 'Coriolanus Snow', 'movies': ['The Hunger Games', 'The Hunger Games: Catching Fire'], 'type': 1}, 
    {'actors': ['George Clooney', 'Frank Sinatra'], 'character': 'Danny Ocean', 'movies': ["Ocean's Eleven (2001)", "Ocean's Eleven (1960)"], 'type': 1}, 
    {'actors': ['Ewan McGregor', 'Danny Lloyd'], 'character': 'Danny Torrance', 'movies': ['Doctor Sleep', 'The Shining'], 'type': 1}, 
    {'actors': ["Chris O'Donnell", 'Logan Lerman'], 'character': "D'Artagnan", 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Gabriel Byrne', "Chris O'Donnell"], 'character': "D'Artagnan", 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['Gabriel Byrne', 'Logan Lerman'], 'character': "D'Artagnan", 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Rex Harrison', 'Eddie Murphy'], 'character': 'Doctor Dolittle', 'movies': ['Doctor Dolittle (1967)', 'Dr. Dolittle'], 'type': 1}, 
    {'actors': ['Robert Downey Jr.', 'Eddie Murphy'], 'character': 'Doctor Dolittle', 'movies': ['Dolittle', 'Dr. Dolittle'], 'type': 1}, 
    {'actors': ['Judy Garland', 'Fairuza Balk'], 'character': 'Dorothy Gale', 'movies': ['The Wizard of Oz', 'Return to Oz'], 'type': 1}, 
    {'actors': ['Arnold Schwarzenegger', 'Colin Farrell'], 'character': 'Douglas Quaid', 'movies': ['Total Recall (1990)', 'Total Recall (2012)'], 'type': 1}, 
    {'actors': ['Bill Skarsgård', 'Nicolas Cage'], 'character': 'Dracula', 'movies': ['Nosferatu (2024)', 'Renfield'], 'type': 1}, 
    {'actors': ['Bill Skarsgård', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Nosferatu (2024)', 'Dracula Untold'], 'type': 1}, 
    {'actors': ['Gary Oldman', 'Luke Evans'], 'character': 'Dracula', 'movies': ["Bram Stoker's Dracula", 'Dracula Untold'], 'type': 1}, 
    {'actors': ['Gary Oldman', 'Bill Skarsgård'], 'character': 'Dracula', 'movies': ["Bram Stoker's Dracula", 'Nosferatu (2024)'], 'type': 1}, 
    {'actors': ['Gary Oldman', 'Nicolas Cage'], 'character': 'Dracula', 'movies': ["Bram Stoker's Dracula", 'Renfield'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Nicolas Cage'], 'character': 'Dracula', 'movies': ['Dracula 2000', 'Renfield'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Dracula 2000', 'Dracula Untold'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Bill Skarsgård'], 'character': 'Dracula', 'movies': ['Dracula 2000', 'Nosferatu (2024)'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Gary Oldman'], 'character': 'Dracula', 'movies': ['Dracula 2000', "Bram Stoker's Dracula"], 'type': 1}, 
    {'actors': ['Nicolas Cage', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Renfield', 'Dracula Untold'], 'type': 1}, 
    {'actors': ['Dennis Christopher', 'Jack Dylan Grazer'], 'character': 'Eddie Kaspbrak', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['Dennis Christopher', 'James Ransone'], 'character': 'Eddie Kaspbrak', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Jack Dylan Grazer', 'James Ransone'], 'character': 'Eddie Kaspbrak', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Bill Skarsgard', 'Brandon Lee'], 'character': 'Eric Draven', 'movies': ['The Crow (2024)', 'The Crow (1994)'], 'type': 1}, 
    {'actors': ['Rachel Weisz', 'Maria Bello'], 'character': "Evelyn 'Evie' Carnahan", 'movies': ['The Mummy, The Mummy Returns', 'The Mummy: Tomb of the Dragon Emperor'], 'type': 1}, 
    {'actors': ['Anya Taylor-Joy', 'Charlize Theron'], 'character': 'Furiosa', 'movies': ['Furiosa: A Mad Max Saga', 'Mad Max: Fury Road'], 'type': 1}, 
    {'actors': ['James Brolin', 'Ryan Reynolds'], 'character': 'George Lutz', 'movies': ['The Amityville Horror (1979)', 'The Amityville Horror (2005)'], 'type': 1}, 
    {'actors': ['Brian Cox', 'Anthony Hopkins'], 'character': 'Hannibal Lecter', 'movies': ['Manhunter', 'The Silence of the Lambs, Red Dragon, Hannibal'], 'type': 1}, 
    {'actors': ['Jeff Daniels', 'Derek Richardson'], 'character': 'Harry Dunne', 'movies': ['Dumb and Dumber', 'Dumb and Dumber To'], 'type': 1}, 
    {'actors': ['Chevy Chase', 'Jon Hamm'], 'character': "Irwin 'Fletch' Fletcher", 'movies': ['Fletch', 'Fletch Lives'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'Harrison Ford'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October', 'Patriot Games, Clear and Present Danger'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'Ben Affleck'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October', 'The Sum of All Fears'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'Chris Pine'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October', 'Jack Ryan: Shadow Recruit'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October', "Tom Clancy's Jack Ryan"], 'type': 1}, 
    {'actors': ['Ben Affleck', 'Chris Pine'], 'character': 'Jack Ryan', 'movies': ['The Sum of All Fears', 'Jack Ryan: Shadow Recruit'], 'type': 1}, 
    {'actors': ['Ben Affleck', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['The Sum of All Fears', "Tom Clancy's Jack Ryan"], 'type': 1}, 
    {'actors': ['Chris Pine', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['Jack Ryan: Shadow Recruit', "Tom Clancy's Jack Ryan"], 'type': 1}, 
    {'actors': ['Harrison Ford', 'Ben Affleck'], 'character': 'Jack Ryan', 'movies': ['Patriot Games, Clear and Present Danger', 'The Sum of All Fears'], 'type': 1}, 
    {'actors': ['Harrison Ford', 'Chris Pine'], 'character': 'Jack Ryan', 'movies': ['Patriot Games, Clear and Present Danger', 'Jack Ryan: Shadow Recruit'], 'type': 1}, 
    {'actors': ['Harrison Ford', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['Patriot Games, Clear and Present Danger', "Tom Clancy's Jack Ryan"], 'type': 1}, 
    {'actors': ['George Lazenby', 'Roger Moore'], 'character': 'James Bond', 'movies': ["On Her Majesty's Secret Service", 'Live and Let Die, The Man with the Golden Gun, The Spy Who Loved Me, Moonraker, For Your Eyes Only, Octopussy, A View to a Kill'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Timothy Dalton'], 'character': 'James Bond', 'movies': ["On Her Majesty's Secret Service", 'The Living Daylights, Licence to Kill'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ["On Her Majesty's Secret Service", 'GoldenEye, Tomorrow Never Dies, The World is Not Enough, Die Another Day'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Daniel Craig'], 'character': 'James Bond', 'movies': ["On Her Majesty's Secret Service", 'Casino Royale, Quantum of Solace, Skyfall, Spectre, No Time To Die'], 'type': 1}, 
    {'actors': ['Pierce Brosnan', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['GoldenEye, Tomorrow Never Dies, The World is Not Enough, Die Another Day', 'Casino Royale, Quantum of Solace, Skyfall, Spectre, No Time To Die'], 'type': 1}, 
    {'actors': ['Roger Moore', 'Timothy Dalton'], 'character': 'James Bond', 'movies': ['Live and Let Die, The Man with the Golden Gun, The Spy Who Loved Me, Moonraker, For Your Eyes Only, Octopussy, A View to a Kill', 'The Living Daylights, Licence to Kill'], 'type': 1}, 
    {'actors': ['Roger Moore', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['Live and Let Die, The Man with the Golden Gun, The Spy Who Loved Me, Moonraker, For Your Eyes Only, Octopussy, A View to a Kill', 'GoldenEye, Tomorrow Never Dies, The World is Not Enough, Die Another Day'], 'type': 1}, 
    {'actors': ['Roger Moore', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['Live and Let Die, The Man with the Golden Gun, The Spy Who Loved Me, Moonraker, For Your Eyes Only, Octopussy, A View to a Kill', 'Casino Royale, Quantum of Solace, Skyfall, Spectre, No Time To Die'], 'type': 1}, 
    {'actors': ['Sean Connery', 'George Lazenby'], 'character': 'James Bond', 'movies': ['Dr. No, From Russia with Love, Goldfinger, Thunderball, You Only Live Twice, Diamonds Are Forever', "On Her Majesty's Secret Service"], 'type': 1}, 
    {'actors': ['Sean Connery', 'Roger Moore'], 'character': 'James Bond', 'movies': ['Dr. No, From Russia with Love, Goldfinger, Thunderball, You Only Live Twice, Diamonds Are Forever', 'Live and Let Die, The Man with the Golden Gun, The Spy Who Loved Me, Moonraker, For Your Eyes Only, Octopussy, A View to a Kill'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Timothy Dalton'], 'character': 'James Bond', 'movies': ['Dr. No, From Russia with Love, Goldfinger, Thunderball, You Only Live Twice, Diamonds Are Forever', 'The Living Daylights, Licence to Kill'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['Dr. No, From Russia with Love, Goldfinger, Thunderball, You Only Live Twice, Diamonds Are Forever', 'GoldenEye, Tomorrow Never Dies, The World is Not Enough, Die Another Day'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['Dr. No, From Russia with Love, Goldfinger, Thunderball, You Only Live Twice, Diamonds Are Forever', 'Casino Royale, Quantum of Solace, Skyfall, Spectre, No Time To Die'], 'type': 1}, 
    {'actors': ['Timothy Dalton', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['The Living Daylights, Licence to Kill', 'GoldenEye, Tomorrow Never Dies, The World is Not Enough, Die Another Day'], 'type': 1}, 
    {'actors': ['Timothy Dalton', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['The Living Daylights, Licence to Kill', 'Casino Royale, Quantum of Solace, Skyfall, Spectre, No Time To Die'], 'type': 1}, 
    {'actors': ['Jake Gyllenhaal', 'Patrick Swayze'], 'character': 'James Dalton', 'movies': ['Road House (1989)', 'Road House (2024)'], 'type': 1}, 
    {'actors': ['Andie MacDowell', 'Margot Robbie'], 'character': 'Jane Porter/Jane Clayton', 'movies': ['Greystoke: The Legend of Tarzan', 'Lord of the Apes'], 'type': 1}, 
    {'actors': ['Elisabeth Shue', 'Claudia Wells'], 'character': 'Jennifer Parker', 'movies': ['Back to the Future II, Back to the Future III', 'Back to the Future'], 'type': 1}, 
    {'actors': ['Joseph Gordon-Levitt', 'Bruce Willis'], 'character': 'Joe', 'movies': ['Looper', 'Looper'], 'type': 1}, 
    {'actors': ['Christopher Lambert', 'Alexander Skarsgård'], 'character': 'John Clayton/Tarzan', 'movies': ['Greystoke: The Legend of Tarzan', 'Lord of the Apes'], 'type': 1}, 
    {'actors': ['Christian Bale', 'Jason Clarke'], 'character': 'John Connor', 'movies': ['Terminator Salvation', 'Terminator Genisys'], 'type': 1}, 
    {'actors': ['Edward Furlong', 'Nick Stahl'], 'character': 'John Connor', 'movies': ['Terminator 2: Judgment Day, Terminator Dark Fate', 'Terminator 3: Rise of the Machines'], 'type': 1}, 
    {'actors': ['Edward Furlong', 'Christian Bale'], 'character': 'John Connor', 'movies': ['Terminator 2: Judgment Day, Terminator Dark Fate', 'Terminator Salvation'], 'type': 1}, 
    {'actors': ['Edward Furlong', 'Jason Clarke'], 'character': 'John Connor', 'movies': ['Terminator 2: Judgment Day, Terminator Dark Fate', 'Terminator Genisys'], 'type': 1}, 
    {'actors': ['Nick Stahl', 'Christian Bale'], 'character': 'John Connor', 'movies': ['Terminator 3: Rise of the Machines', 'Terminator Salvation'], 'type': 1}, 
    {'actors': ['Nick Stahl', 'Jason Clarke'], 'character': 'John Connor', 'movies': ['Terminator 3: Rise of the Machines', 'Terminator Genisys'], 'type': 1}, 
    {'actors': ['Keanu Reeves', 'Luke Bracey'], 'character': 'Johnny Utah', 'movies': ['Point Break (1991)', 'Point Break (2015)'], 'type': 1}, 
    {'actors': ['Sylvester Stallone', 'Karl Urban'], 'character': 'Judge Dredd', 'movies': ['Judge Dredd', 'Dredd'], 'type': 1}, 
    {'actors': ['Margot Kidder', 'Melissa George'], 'character': 'Kathy Lutz', 'movies': ['The Amityville Horror (1979)', 'The Amityville Horror (2005)'], 'type': 1}, 
    {'actors': ['Anton Yelchin', 'Jai Courtney'], 'character': 'Kyle Reese', 'movies': ['Terminator Salvation', 'Terminator Genisys'], 'type': 1}, 
    {'actors': ['Michael Biehn', 'Anton Yelchin'], 'character': 'Kyle Reese', 'movies': ['Terminator', 'Terminator Salvation'], 'type': 1}, 
    {'actors': ['Angelina Jolie', 'Alicia Vikander'], 'character': 'Lara Croft', 'movies': ['Lara Croft: Tomb Raider, Lara Croft: Tomb Raider - The Cradle of Life', 'Tomb Raider'], 'type': 1}, 
    {'actors': ['Tom Cruise', 'Stuart Townsend'], 'character': 'Lestat de Lioncourt', 'movies': ['Interview with the Vampire', 'Queen of the Damned'], 'type': 1}, 
    {'actors': ['Tom Cruise', 'Sam Reid'], 'character': 'Lestat de Lioncourt', 'movies': ['Interview with the Vampire', 'Interview with the Vampire (TV)'], 'type': 1}, 
    {'actors': ['Humphrey Bogart', 'Harrison Ford'], 'character': 'Linus Larrabee', 'movies': ['Sabrina (1954)', 'Sabrina (1995)'], 'type': 1}, 
    {'actors': ['Jim Carrey', 'Eric Christian Olsen'], 'character': 'Lloyd Christmas', 'movies': ['Dumb and Dumber', 'Dumb and Dumber To'], 'type': 1}, 
    {'actors': ['Sharon Stone', 'Kate Beckinsale'], 'character': 'Lori Quaid', 'movies': ['Total Recall (1990)', 'Total Recall (2012)'], 'type': 1}, 
    {'actors': ['Julie Andrews', 'Emily Blunt'], 'character': 'Mary Poppins', 'movies': ['Mary Poppins', 'Mary Poppins Returns'], 'type': 1}, 
    {'actors': ['Tom Hardy', 'Mel Gibson'], 'character': 'Max Rockatansky', 'movies': ['Mad Max: Fury Road', 'Mad Mad'], 'type': 1}, 
    {'actors': ['Chosen Jacobs', 'Isaiah Mustafa'], 'character': 'Mike Hanlon', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Tim Reid', 'Chosen Jacobs'], 'character': 'Mike Hanlon', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['Tim Reid', 'Isaiah Mustafa'], 'character': 'Mike Hanlon', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Ewan McGregor', 'Alec Guiness'], 'character': 'Obi-Wan Kenobi', 'movies': ['Star Wars: Episode I - The Phantom Menace, Star Wars: Episode II - Attack of the Clones, Star Wars: Episode III – Revenge of the Sith, Obi-Wan Kenobi', 'Star Wars: Episode IV - A New Hope, Star Wars: Episode V - The Empire Strikes Back, Star Wars: Episode VI - Return of the Jedi'], 'type': 1}, 
    {'actors': ['Timothée Chalamet', 'Kyle MacLachlan'], 'character': 'Paul Atreides', 'movies': ['Dune: Part One', 'Dune'], 'type': 1}, 
    {'actors': ['Tim Curry', 'Bill Skarsgård'], 'character': 'Pennywise', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['Gerard Depardieu', 'Oliver Platt'], 'character': 'Porthos', 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['Gerard Depardieu', 'Ray Stevenson'], 'character': 'Porthos', 'movies': ['The Man in the Iron Mask', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Oliver Platt', 'Ray Stevenson'], 'character': 'Porthos', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Rachel McAdams', 'Reneé Rapp'], 'character': 'Regina George', 'movies': ['Mean Girls (2004)', 'Mean Girls (2024)'], 'type': 1}, 
    {'actors': ['Finn Wolfhard', 'Bill Hader'], 'character': 'Richie Tozier', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Harry Anderson', 'Finn Wolfhard'], 'character': 'Richie Tozier', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['Harry Anderson', 'Bill Hader'], 'character': 'Richie Tozier', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Kevin Costner', 'Russell Crowe'], 'character': 'Robin Hood', 'movies': ['Robin Hood: Prince of Thieves', 'Robin Hood'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Taron Egerton'], 'character': 'Robin Hood', 'movies': ['Robin Hood', 'Robin and Marian'], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Jason Lively'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Vacation", "National Lampoon's European Vacation"], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Johnny Galecki'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Vacation", "National Lampoon's Christmas Vacation"], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Ethan Embry'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Vacation", "National Lampoon's Vegas Vacation"], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Ethan Embry', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Vegas Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Jason Lively', 'Johnny Galecki'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's European Vacation", "National Lampoon's Christmas Vacation"], 'type': 1}, 
    {'actors': ['Jason Lively', 'Ethan Embry'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's European Vacation", "National Lampoon's Vegas Vacation"], 'type': 1}, 
    {'actors': ['Jason Lively', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's European Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Johnny Galecki', 'Ethan Embry'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Christmas Vacation", "National Lampoon's Vegas Vacation"], 'type': 1}, 
    {'actors': ['Johnny Galecki', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ["National Lampoon's Christmas Vacation", 'Vacation'], 'type': 1}, 
    {'actors': ['Brad Pitt', 'Dean Martin'], 'character': 'Rusty Ryan', 'movies': ["Ocean's Eleven (2001)", "Ocean's Eleven (1960)"], 'type': 1}, 
    {'actors': ['Audrey Hepburn', 'Julia Ormond'], 'character': 'Sabrina Fairchild', 'movies': ['Sabrina (1954)', 'Sabrina (1995)'], 'type': 1}, 
    {'actors': ['Kurt Russell', 'Tim Allen'], 'character': 'Santa Claus', 'movies': ['The Christmas Chronicles', 'The Christmas Chronicles: Part 2'], 'type': 1}, 
    {'actors': ['Henry Cavill', 'Robert Downey Jr.'], 'character': 'Sherlock Homes', 'movies': ['Enola Holmes', 'Enola Holmes 2'], 'type': 1}, 
    {'actors': ['Kristen Stewart', 'Rachel Zegler'], 'character': 'Snow White', 'movies': ['Snow White and the Huntsman', 'Snow White'], 'type': 1}, 
    {'actors': ['Richard Masur', 'Wyatt Oleff'], 'character': 'Stanley Uris', 'movies': ['It (1990)', 'It'], 'type': 1}, 
    {'actors': ['Richard Masur', 'Andy Bean'], 'character': 'Stanley Uris', 'movies': ['It (1990)', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Wyatt Oleff', 'Andy Bean'], 'character': 'Stanley Uris', 'movies': ['It', 'It: Chapter 2'], 'type': 1}, 
    {'actors': ['Frank Morgan', 'Jeff Goldblum'], 'character': 'The Wizard of Oz', 'movies': ['The Wizard of Oz', 'Wicked'], 'type': 1}, 
    {'actors': ['James Franko', 'Jeff Goldblum'], 'character': 'The Wizard of Oz', 'movies': ['Oz the Great and Powerful', 'Wicked'], 'type': 1}, 
    {'actors': ['James Franko', 'Frank Morgan'], 'character': 'The Wizard of Oz', 'movies': ['Oz the Great and Powerful', 'The Wizard of Oz'], 'type': 1}, 
    {'actors': ['Rachelle Lefevre', 'Bryce Dallas Howard'], 'character': 'Victoria', 'movies': ['Twilight', 'The Twilight Saga: New Moon'], 'type': 1}, 
    {'actors': ['Robert De Niro', 'Marlon Brando'], 'character': 'Vito Corleone ', 'movies': ['The Godfather: Part II', 'The Godfather '], 'type': 1}, 
    {'actors': ['Ben Stiller', 'Danny Kaye'], 'character': 'Walter Mitty', 'movies': ['The Secret Life of Walter Mitty (2013)', 'The Secret Life of Walter Mitty (1947)'], 'type': 1}, 
    {'actors': ['Gene Wilder', 'Johnny Depp'], 'character': 'Willy Wonka', 'movies': ['Willy Wonka and the Chocolate Factory', 'Charlie and the Chocolate Factory'], 'type': 1}, 
    {'actors': ['Gene Wilder', 'Timothée Chalamet'], 'character': 'Willy Wonka', 'movies': ['Willy Wonka and the Chocolate Factory', 'Wonka'], 'type': 1}, 
    {'actors': ['Johnny Depp', 'Timothée Chalamet'], 'character': 'Willy Wonka', 'movies': ['Charlie and the Chocolate Factory', 'Wonka'], 'type': 1}, 
    {'actors': ['Harrison Ford', 'Alden Ehrenreich'], 'character': 'Han Solo', 'movies': ['Star Wars: Episode IV - A New Hope, Star Wars: Episode V - The Empire Strikes Back, Star Wars: Episode VI - Return of the Jedi, Star Wars: Episode VII - The Force Awakens, Star War: Episode IX - The Rise of Skywalker', 'Solo: A Star Wars Story'], 'type': 1}, 
    {'actors': ['Billy Dee Williams', 'Donald Glover'], 'character': 'Lando Calrissian ', 'movies': ['Star Wars: Episode V - The Empire Strikes Back, Star Wars: Episode VI - Return of the Jedi, Star War: Episode IX - The Rise of Skywalker', 'Solo: A Star Wars Story'], 'type': 1}, 
    {'actors': ['Anthony Perkins', 'Vince Vaughn'], 'character': 'Norman Bates', 'movies': ['Psycho, Psycho II, Psycho III, Psycho IV', 'Psycho (1998)'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Christian Bale'], 'character': 'Moses', 'movies': ['The Ten Commandments', 'Exodus: Gods and Kings'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Val Kilmer'], 'character': 'Moses', 'movies': ['The Ten Commandments', 'The Prince of Egypt'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Ben Kinglsey'], 'character': 'Moses', 'movies': ['The Ten Commandments', 'Moses'], 'type': 1}, 
    {'actors': ['Christian Bale', 'Val Kilmer'], 'character': 'Moses', 'movies': ['Exodus: Gods and Kings', 'The Prince of Egypt'], 'type': 1}, 
    {'actors': ['Christian Bale', 'Ben Kinglsey'], 'character': 'Moses', 'movies': ['Exodus: Gods and Kings', 'Moses'], 'type': 1}, 
    {'actors': ['Val Kilmer', 'Ben Kinglsey'], 'character': 'Moses', 'movies': ['The Prince of Egypt', 'Moses'], 'type': 1}, 
    {'actors': ['John Wayne', 'Jeff Bridges'], 'character': 'Rooster Cogburn', 'movies': ['True Grit (1969)', 'True Grit (2010)'], 'type': 1}, 
    {'actors': ['Glen Campbell', 'Matt Damon'], 'character': 'LaBoeuf', 'movies': ['True Grit (1969)', 'True Grit (2010)'], 'type': 1}, 
    {'actors': ['Emma Roberts', 'Sophia Lillis'], 'character': 'Nancy Drew', 'movies': ['Nancy Drew', 'Nancy Drew and the Hiden Staircase'], 'type': 1}, 
    {'actors': ['Sissy Spacek', 'Chloe Grace Moretz'], 'character': 'Carrie White', 'movies': ['Carrie (1976)', 'Carrie (2013)'], 'type': 1}, 
    {'actors': ['Jason Clarke', 'Dale Midkiff'], 'character': 'Louis Creed', 'movies': ['Pet Sematary (2019)', 'Pet Sematary (1989)'], 'type': 1}, 
    {'actors': ['Amy Seimetz', 'Denise Crosby'], 'character': 'Rachel Creed', 'movies': ['Pet Sematary (2019)', 'Pet Sematary (1989)'], 'type': 1}, 
    {'actors': ['John Lithgow', 'Fred Gwynne'], 'character': 'Jud', 'movies': ['Pet Sematary (2019)', 'Pet Sematary (1989)'], 'type': 1}
];
