// Card Type 3 cards
export const cardDataType3 = [
    {'actors': ['Alessandra Torresani', 'Mae Whitman'], 'character': 'Ann Veal', 'movies': ['Arrested Development (TV) (2003)'], 'type': 3}, 
    {'actors': ['Dick York', 'Dick Sargent'], 'character': 'Darrin Stephens', 'movies': ['Bewitched (TV) (1964)'], 'type': 3}, 
    {'actors': ['Tommy Lee Miller', 'Benedict Cumberbatch'], 'character': 'Sherlock Holmes', 'movies': ['Elementary (TV) (2012)', 'Sherlock (TV) (2010)'], 'type': 3}, 
    {'actors': ['Will Smith', 'Jabari Banks'], 'character': 'Will Smith', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['James Avery', 'Adrian Holmes'], 'character': 'Philip Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Alfonso Ribeiro', 'Olly Sholotan'], 'character': 'Carlton Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Tatyana Ali', 'Akira Akbar'], 'character': 'Ashley Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Karyn Parsons', 'Coco Jones'], 'character': 'Hilary Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Joseph Marcell', 'Jimmy Akingbola'], 'character': 'Geoffrey', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Daphne Reid', 'Cassandra Freeman'], 'character': 'Vivian Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Janet Hubert-Whitten', 'Cassandra Freeman'], 'character': 'Vivian Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['DJ Jazzy Jeff', 'Jordan L. Jones'], 'character': 'Jazz', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)', 'Bel-Air (TV) (2022)'], 'type': 3}, 
    {'actors': ['Anita Barone', 'Jane Sibbett'], 'character': 'Carol Willick-Bunch', 'movies': ['Friends (TV) (1994)'], 'type': 3}, 
    {'actors': ['Scott Caan', 'James MacArthur'], 'character': 'Danny Williams', 'movies': ['Hawaii Five-0 (TV) (2010)', 'Hawaii Five-0 (TV) (1968)'], 'type': 3}, 
    {'actors': ['Alex O\'Loughlin', 'Jack Lord'], 'character': 'Steve McGarrett', 'movies': ['Hawaii Five-0 (TV) (2010)', 'Hawaii Five-0 (TV) (1968)'], 'type': 3}, 
    {'actors': ['Telly Savalas', 'Ving Rhames'], 'character': 'Theo Kojak', 'movies': ['Kojak (TV) (1973)', 'Kojak (TV) (2005)'], 'type': 3}, 
    {'actors': ['Molly Parker', 'Jane Lockhart'], 'character': 'Maureen Robinson', 'movies': ['Lost in Space (TV) (2018)', 'Lost in Space (TV) (1965)'], 'type': 3}, 
    {'actors': ['Toby Stephens', 'Guy Williams'], 'character': 'John Robinson', 'movies': ['Lost in Space (TV) (2018)', 'Lost in Space (TV) (1965)'], 'type': 3}, 
    {'actors': ['Maxwell Jenkins', 'Bill Mumy'], 'character': 'Will Robionson', 'movies': ['Lost in Space (TV) (2018)', 'Lost in Space (TV) (1965)'], 'type': 3}, 
    {'actors': ['Taylor Russell', 'Marta Kristen'], 'character': 'Judy Robinson', 'movies': ['Lost in Space (TV) (2018)', 'Lost in Space (TV) (1965)'], 'type': 3}, 
    {'actors': ['Mina Sundwall', 'Angela Cartwright'], 'character': 'Penny Robinson', 'movies': ['Lost in Space (TV) (2018)', 'Lost in Space (TV) (1965)'], 'type': 3}, 
    {'actors': ['Ignacio Serricchio', 'Mark Goddard'], 'character': 'Don West', 'movies': ['Lost in Space (TV) (2018)', 'Lost in Space (TV) (1965)'], 'type': 3}, 
    {'actors': ['Richard Dean Anderson', 'Lucal Till'], 'character': 'MacGyver', 'movies': ['MacGyver (TV) (1985)', 'MacGyver (TV) (2016)'], 'type': 3}, 
    {'actors': ['Tom Selleck', 'Jay Hernandez'], 'character': 'Thomas Magnum', 'movies': ['Magnum P.I. (TV) (1980)', 'Magnum P.I. (TV) (2018)'], 'type': 3}, 
    {'actors': ['Maggie Q', 'Peta Wilson'], 'character': 'Nikita', 'movies': ['Nikita (TV) (2010)', 'La Femme Nikita (TV) (1997)'], 'type': 3}, 
    {'actors': ['Matthew Rhys', 'Raymond Burr'], 'character': 'Perry Mason', 'movies': ['Perry Mason (TV) (2020)', 'Perry Mason (TV) (1957)'], 'type': 3}, 
    {'actors': ['Alicia “Lecy” Goranson', 'Sarah Chalke'], 'character': 'Rebecca “Becky” Conner-Healy', 'movies': ['Roseanne (TV) (1998)'], 'type': 3}, 
    {'actors': ['Melissa Joan Hart', 'Kiernan Shipka'], 'character': 'Sabrina Spellman', 'movies': ['Sabrina, The Teenage Witch (TV) (1996)', 'Chilling Adventures of Sabrina (TV) (2018)'], 'type': 3}, 
    {'actors': ['Caroline Rhea', 'Lucy Davis'], 'character': 'Hilda Spellman', 'movies': ['Sabrina, The Teenage Witch (TV) (1996)', 'Chilling Adventures of Sabrina (TV) (2018)'], 'type': 3}, 
    {'actors': ['Beth Broderick', 'Miranda Otto'], 'character': 'Zelda Spellman', 'movies': ['Sabrina, The Teenage Witch (TV) (1996)', 'Chilling Adventures of Sabrina (TV) (2018)'], 'type': 3}, 
    {'actors': ['Nate Richert', 'Ross Lynch'], 'character': 'Harvey Kinkle', 'movies': ['Sabrina, The Teenage Witch (TV) (1996)', 'Chilling Adventures of Sabrina (TV) (2018)'], 'type': 3}, 
    {'actors': ['Lisa Robin Kelly', 'Christina Moore'], 'character': 'Laurie Forman', 'movies': ['That ’70s Show (TV) (1998)'], 'type': 3}, 
    {'actors': ['Lisa Loring', 'Jenna Ortega'], 'character': 'Wednesday Addams', 'movies': ['The Addams Family (TV) (1964)', 'Wednesday (TV) (2022)'], 'type': 3}, 
    {'actors': ['John Astin', 'Luis Guzmán'], 'character': 'Gomez Addams', 'movies': ['The Addams Family (TV) (1964)', 'Wednesday (TV) (2022)'], 'type': 3}, 
    {'actors': ['Carolyn Jones', 'Catherine Zeta-Jones'], 'character': 'Morticia Addams', 'movies': ['The Addams Family (TV) (1964)', 'Wednesday (TV) (2022)'], 'type': 3}, 
    {'actors': ['Ken Weatherwax', 'Isaac Ordonez'], 'character': 'Pugsley Addams', 'movies': ['The Addams Family (TV) (1964)', 'Wednesday (TV) (2022)'], 'type': 3}, 
    {'actors': ['Jackie Coogan', 'Fred Armisen'], 'character': 'Uncle Fester Addams', 'movies': ['The Addams Family (TV) (1964)', 'Wednesday (TV) (2022)'], 'type': 3}, 
    {'actors': ['Michelle Ryan', 'Lindsay Wagner'], 'character': 'Jaime Sommers', 'movies': ['The Bionic Woman (TV) (2007)', 'The Bionic Woman (TV) (1976)'], 'type': 3}, 
    {'actors': ['Janet Hubert-Whitten', 'Daphne Reid'], 'character': 'Vivian Banks', 'movies': ['Fresh Prince of Bel-Air (TV) (1990)'], 'type': 3}, 
    {'actors': ['Shailene Woodley', 'Willa Holland'], 'character': 'Kaitlin Cooper', 'movies': ['The O.C. (TV) (2003)'], 'type': 3}, 
    {'actors': ['Matthew Perry', 'Tony Randall'], 'character': 'Oscar Madison', 'movies': ['The Odd Couple (TV) (2015)', 'The Odd Couple (TV) (1970)'], 'type': 3}, 
    {'actors': ['Thomas Lennon', 'Jack Klugman'], 'character': 'Felix Unger', 'movies': ['The Odd Couple (TV) (2015)', 'The Odd Couple (TV) (1970)'], 'type': 3}, 
    {'actors': ['Henry Cavill', 'Liam Hemsworth'], 'character': 'Geralt of Rivia', 'movies': ['The Witcher (TV) (2019)'], 'type': 3}, 
    {'actors': ['Chuck Norris', 'Jared Padalecki'], 'character': 'Cordell Walker', 'movies': ['Walker, Texas Ranger (TV) (1993)', 'Walker (TV) (2001)'], 'type': 3}, 
    {'actors': ['Iain Armitage', 'Jim Parsons'], 'character': 'Sheldon Cooper', 'movies': ['Young Sheldon (TV) (2017)', 'The Big Bang Theory (TV) (2007)'], 'type': 3}, 
    {'actors': ['Gary Sinise', 'James Marsden'], 'character': 'Stu Redman', 'movies': ['The Stand (TV) (1994)', 'The Stand (TV) (2020)'], 'type': 3}, 
    {'actors': ['Molly Ringwald', 'Odessa Young'], 'character': 'Frannie Goldsmith', 'movies': ['The Stand (TV) (1994)', 'The Stand (TV) (2020)'], 'type': 3}, 
    {'actors': ['Jamey Sheridan', 'Alexander Skarsgard'], 'character': 'Randal Flagg', 'movies': ['The Stand (TV) (1994)', 'The Stand (TV) (2020)'], 'type': 3}, 
    {'actors': ['Laura San Giacomo', 'Amber Heard'], 'character': 'Nadine Cross', 'movies': ['The Stand (TV) (1994)', 'The Stand (TV) (2020)'], 'type': 3}, 
    {'actors': ['Ruby Dee', 'Whoopi Golderg'], 'character': 'Mother Abagail Freemantle', 'movies': ['The Stand (TV) (1994)', 'The Stand (TV) (2020)'], 'type': 3}, 
    {'actors': ['David Soul', 'Rob Lowe'], 'character': 'Ben Mears', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['David Soul', 'Lewis Pullman'], 'character': 'Ben Mears', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['Rob Lowe', 'Lewis Pullman'], 'character': 'Ben Mears', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['Bonnie Bedelia', 'Samantha Mathis'], 'character': 'Susan Norton', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['Bonnie Bedelia', 'Makenzie Leigh'], 'character': 'Susan Norton', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['Samantha Mathis', 'Makenzie Leigh'], 'character': 'Susan Norton', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['Andre Braugher', 'Bill Camp'], 'character': 'Matt Burke', 'movies': ['Salem\'s Lot (TV) (1979)', 'Salem\'s Lot (TV) (2004)'], 'type': 3}, 
    {'actors': ['Sarah Jessica Parker', 'AnnaSophia Rob'], 'character': 'Carrie Bradshaw', 'movies': ['Sex and the City (TV) (1998)', 'The Carrie Diaries (TV) (2013)'], 'type': 3} 
];
