// Card Type 1 cards
export const cardDataType1 = [
    {'actors': ['Timothy Olyphant', 'Rupert Friend'], 'character': 'Agent 47', 'movies': ['Hitman (2007)', 'Hitman: Agent 47 (2015)'], 'type': 1}, 
    {'actors': ['Tommy Lee Jones', 'Josh Brolin'], 'character': 'Agent K', 'movies': ['Men in Black 3 (2012)'], 'type': 1}, 
    {'actors': ['Jude Law', 'Richard Harris'], 'character': 'Albus Dumbledore', 'movies': ['Fantastic Beasts: The Crimes of Grindelwald (2018)', 'Fantastic Beasts: The Secrets of Dumbledore (2022)'], 'type': 1}, 
    {'actors': ['Jude Law', 'Michael Gambon'], 'character': 'Albus Dumbledore', 'movies': ['Fantastic Beasts: The Crimes of Grindelwald (2018)', 'Fantastic Beasts: The Secrets of Dumbledore (2022)'], 'type': 1}, 
    {'actors': ['Richard Harris', 'Michael Gambon'], 'character': 'Albus Dumbledore', 'movies': ['Harry Potter and the Philosopher\'s Stone (2001)', 'Harry Potter and the Chamber of Secrets (2002)'], 'type': 1}, 
    {'actors': ['Peter Weller', 'Joel Kinnaman'], 'character': 'Alex Murphy', 'movies': ['RoboCop (1987), RoboCop 2 (1990)', 'RoboCop (2014)'], 'type': 1}, 
    {'actors': ['Michael Caine', 'Jude Law'], 'character': 'Alfie', 'movies': ['Alfie (1966)', 'Alfie (2004)'], 'type': 1}, 
    {'actors': ['Florence Pugh', 'Kirseten Dunst'], 'character': 'Amy March', 'movies': ['Little Woman (2019)', 'Little Women (1994)'], 'type': 1}, 
    {'actors': ['Hayden Christensen', 'Jake Lloyd'], 'character': 'Anakin Skywalker', 'movies': ['Star Wars: Episode II - Attack of the Clones (2002), Star Wars: Episode III – Revenge of the Sith (2005)', 'Star Wars: Episode I - The Phantom Menace (1999)'], 'type': 1}, 
    {'actors': ['David Keith', 'Zac Efron'], 'character': 'Andrew McGee', 'movies': ['Firestarter (1984)', 'Firestarter (2022)'], 'type': 1}, 
    {'actors': ['Aileen Quinn', 'Quvenzhane Wallis'], 'character': 'Annie', 'movies': ['Annie (1982)', 'Annie (2014)'], 'type': 1}, 
    {'actors': ['Jeremy Irons', 'Charlie Sheen'], 'character': 'Aramis', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['Jeremy Irons', 'Luke Evans'], 'character': 'Aramis', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Charlie Sheen', 'Luke Evans'], 'character': 'Aramis', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['John Malkovich', 'Kiefer Sutherland'], 'character': 'Athos', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['John Malkovich', 'Matthew Macfadyen'], 'character': 'Athos', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Kiefer Sutherland', 'Matthew Macfadyen'], 'character': 'Athos', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Dana Hill', 'Juliette Lewis'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'National Lampoon\'s Christmas Vacation (1989)'], 'type': 1}, 
    {'actors': ['Dana Hill', 'Marisol Nichols'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'National Lampoon\'s Vegas Vacation (1997)'], 'type': 1}, 
    {'actors': ['Dana Hill', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Juliette Lewis', 'Marisol Nichols'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'National Lampoon\'s Vegas Vacation (1997)'], 'type': 1}, 
    {'actors': ['Juliette Lewis', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Dana Barron', 'Juliette Lewis'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'National Lampoon\'s Christmas Vacation (1989)'], 'type': 1}, 
    {'actors': ['Dana Barron', 'Dana Hill'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'National Lampoon\'s European Vacation (1985)'], 'type': 1}, 
    {'actors': ['Dana Barron', 'Marisol Nichols'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'National Lampoon\'s Vegas Vacation (1997)'], 'type': 1}, 
    {'actors': ['Dana Barron', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Marisol Nichols', 'Leslie Mann'], 'character': 'Audrey Griswold', 'movies': ['National Lampoon\'s Vegas Vacation (1997)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['John Ritter', 'Jay Ryan'], 'character': 'Ben Hanscom', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['John Ritter', 'Jeremy Ray Taylor'], 'character': 'Ben Hanscom', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Jeremy Ray Taylor', 'Jay Ryan'], 'character': 'Ben Hanscom', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Denzel Washington', 'Frank Sinatra'], 'character': 'Ben Marco', 'movies': ['The Manchurian Candidate (2004)', 'The Manchurian Candidate (1962)'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Jack Huston'], 'character': 'Ben-Hur', 'movies': ['Ben-Hur (1959)'], 'type': 1}, 
    {'actors': ['Eliza Scanlen', 'Claire Danes'], 'character': 'Beth March', 'movies': ['Little Woman (2019)', 'Little Women (1994)'], 'type': 1}, 
    {'actors': ['Annette O\'Toole', 'Jessica Chastain'], 'character': 'Beverly Marsh', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Annette O\'Toole', 'Sophia Lillis'], 'character': 'Beverly Marsh', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Sophia Lillis', 'Jessica Chastain'], 'character': 'Beverly Marsh', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Martin Freeman', 'Ian Holm'], 'character': 'Bilbo Baggins', 'movies': ['The Hobbit: An Unexpected Journey (2012), The Hobbit: The Desolation of Smaug (2013), The Hobbit: The Battle of the Five Armies (2014)', 'The Lord of the Rings: The Fellowship of the Ring (2001), The Lord of the Rings: The Return of the King (2003), The Hobbit: An Unexpected Journey (2012), The Hobbit: The Battle of the Five Armies (2014)'], 'type': 1}, 
    {'actors': ['Richard Thomas', 'James McAvoy'], 'character': 'Bill Denbrough', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Richard Thomas', 'Jaeden Martell'], 'character': 'Bill Denbrough', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Jaeden Martell', 'James McAvoy'], 'character': 'Bill Denbrough', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Patrick Swayze', 'Edgar Ramírez'], 'character': 'Bodhi', 'movies': ['Point Break (1991)', 'Point Break (2015)'], 'type': 1}, 
    {'actors': ['Lindsay Lohan', 'Angourie Rice'], 'character': 'Cady Heron', 'movies': ['Mean Girls (2004)', 'Mean Girls (2024)'], 'type': 1}, 
    {'actors': ['Sissy Spacek', 'Chloe Grace Moretz'], 'character': 'Carrie White', 'movies': ['Carrie (1976)', 'Carrie (2013)'], 'type': 1}, 
    {'actors': ['Anton Yelchin', 'William Ragsdale'], 'character': 'Charley Brewster', 'movies': ['Fright Night (2011)', 'Fright Night (1985), Fright Night Part 2 (1988)'], 'type': 1}, 
    {'actors': ['Michael Caine', 'Mark Wahlberg'], 'character': 'Charlie Crocker', 'movies': ['The Italian Job (1969)', 'The Italian Job (2003)'], 'type': 1}, 
    {'actors': ['Drew Barrymore', 'Ryan Kiera Armstrong'], 'character': 'Charlie McGee', 'movies': ['Firestarter (1984)', 'Firestarter (2022)'], 'type': 1}, 
    {'actors': ['Anna Kendrick', 'Lily James'], 'character': 'Cinderella', 'movies': ['Into the Woods (2014)', 'Cinderella (2015)'], 'type': 1}, 
    {'actors': ['Jodie Foster', 'Julianne Moore'], 'character': 'Clarice Starling', 'movies': ['The Silence of the Lambs (1991)', 'Hannibal (2001)'], 'type': 1}, 
    {'actors': ['Jason Momoa', 'Arnold Schwarzenegger'], 'character': 'Conan', 'movies': ['Conan the Barbarian (2011)', 'Conan the Barbarian (1982)'], 'type': 1}, 
    {'actors': ['Donald Sutherland', 'Tom Blyth'], 'character': 'Coriolanus Snow', 'movies': ['The Hunger Games (2012), The Hunger Games: Catching Fire (2013), The Hunger Games: Mockingjay - Part 1 (2014), The Hunger Games: Mockingjay - Part 2 (2015)', 'The Hunger Games: The Ballad of Songbirds & Snakes (2023)'], 'type': 1}, 
    {'actors': ['Glen Close', 'Emma Stone'], 'character': 'Cruella DeVil', 'movies': ['101 Dalmations (1996), 102 Dalmations (2000)', 'Cruella (2021)'], 'type': 1}, 
    {'actors': ['Mia Farrow', 'Carey Mulligan'], 'character': 'Daisy Buchanan', 'movies': ['The Great Gatsby (1974)', 'The Great Gatsby (2013)'], 'type': 1}, 
    {'actors': ['George Clooney', 'Frank Sinatra'], 'character': 'Danny Ocean', 'movies': ['Ocean\'s Eleven (2001)', 'Ocean\'s Eleven (1960)'], 'type': 1}, 
    {'actors': ['Ewan McGregor', 'Danny Lloyd'], 'character': 'Danny Torrance', 'movies': ['Doctor Sleep (2019)', 'The Shining (1980)'], 'type': 1}, 
    {'actors': ['Gabriel Byrne', 'Chris O\'Donnell'], 'character': 'D\'Artagnan', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['Gabriel Byrne', 'Logan Lerman'], 'character': 'D\'Artagnan', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Chris O\'Donnell', 'Logan Lerman'], 'character': 'D\'Artagnan', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Jim Carrey', 'George Segal'], 'character': 'Dick Harper', 'movies': ['Fun with Dick and Jane (2005)', 'Fun with Dick and Jane (1977)'], 'type': 1}, 
    {'actors': ['Rex Harrison', 'Eddie Murphy'], 'character': 'Doctor Dolittle', 'movies': ['Doctor Dolittle (1967)', 'Dr. Dolittle (1998), Dr. Dolittle 2 (2001)'], 'type': 1}, 
    {'actors': ['Robert Downey Jr.', 'Eddie Murphy'], 'character': 'Doctor Dolittle', 'movies': ['Dolittle (2020)', 'Dr. Dolittle (1998), Dr. Dolittle 2 (2001)'], 'type': 1}, 
    {'actors': ['Judy Garland', 'Fairuza Balk'], 'character': 'Dorothy Gale', 'movies': ['The Wizard of Oz (1939)', 'Return to Oz (1985)'], 'type': 1}, 
    {'actors': ['Arnold Schwarzenegger', 'Colin Farrell'], 'character': 'Douglas Quaid', 'movies': ['Total Recall (1990)', 'Total Recall (2012)'], 'type': 1}, 
    {'actors': ['Gary Oldman', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Bram Stoker\'s Dracula (1992)', 'Dracula Untold (2014)'], 'type': 1}, 
    {'actors': ['Gary Oldman', 'Bill Skarsgård'], 'character': 'Dracula', 'movies': ['Bram Stoker\'s Dracula (1992)', 'Nosferatu (2024)'], 'type': 1}, 
    {'actors': ['Gary Oldman', 'Nicolas Cage'], 'character': 'Dracula', 'movies': ['Bram Stoker\'s Dracula (1992)', 'Renfield (2023)'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Gary Oldman'], 'character': 'Dracula', 'movies': ['Dracula 2000 (2000)', 'Bram Stoker\'s Dracula (1992)'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Dracula 2000 (2000)', 'Dracula Untold (2014)'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Bill Skarsgård'], 'character': 'Dracula', 'movies': ['Dracula 2000 (2000)', 'Nosferatu (2024)'], 'type': 1}, 
    {'actors': ['Gerard Butler', 'Nicolas Cage'], 'character': 'Dracula', 'movies': ['Dracula 2000 (2000)', 'Renfield (2023)'], 'type': 1}, 
    {'actors': ['Bill Skarsgård', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Nosferatu (2024)', 'Dracula Untold (2014)'], 'type': 1}, 
    {'actors': ['Bill Skarsgård', 'Nicolas Cage'], 'character': 'Dracula', 'movies': ['Nosferatu (2024)', 'Renfield (2023)'], 'type': 1}, 
    {'actors': ['Nicolas Cage', 'Luke Evans'], 'character': 'Dracula', 'movies': ['Renfield (2023)', 'Dracula Untold (2014)'], 'type': 1}, 
    {'actors': ['Dennis Christopher', 'James Ransone'], 'character': 'Eddie Kaspbrak', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Dennis Christopher', 'Jack Dylan Grazer'], 'character': 'Eddie Kaspbrak', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Jack Dylan Grazer', 'James Ransone'], 'character': 'Eddie Kaspbrak', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Bill Skarsgard', 'Brandon Lee'], 'character': 'Eric Draven', 'movies': ['The Crow (2024)', 'The Crow (1994)'], 'type': 1}, 
    {'actors': ['Rachel Weisz', 'Maria Bello'], 'character': 'Evelyn \'Evie\' Carnahan', 'movies': ['The Mummy (1999), The Mummy Returns (2001)', 'The Mummy: Tomb of the Dragon Emperor (2008)'], 'type': 1}, 
    {'actors': ['Dennis Quaid', 'James Stewart'], 'character': 'Frank Towns', 'movies': ['Fkight of the Phoenix (2004)', 'The Flight of the Phoenix (1965)'], 'type': 1}, 
    {'actors': ['Robert Englund', 'James Earle Haley'], 'character': 'Freddy Krueger', 'movies': ['A Nightmare on Elm Street (1984)', 'A Nightmare on Elm Street (2011)'], 'type': 1}, 
    {'actors': ['Anya Taylor-Joy', 'Charlize Theron'], 'character': 'Furiosa', 'movies': ['Furiosa: A Mad Max Saga (2024)', 'Mad Max: Fury Road (2015)'], 'type': 1}, 
    {'actors': ['James Brolin', 'Ryan Reynolds'], 'character': 'George Lutz', 'movies': ['The Amityville Horror (1979)', 'The Amityville Horror (2005)'], 'type': 1}, 
    {'actors': ['Harrison Ford', 'Alden Ehrenreich'], 'character': 'Han Solo', 'movies': ['Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Star Wars: Episode VI - Return of the Jedi (1983), Star Wars: Episode VII - The Force Awakens (2015), Star War: Episode IX - The Rise of Skywalker (2019)', 'Solo: A Star Wars Story (2018)'], 'type': 1}, 
    {'actors': ['Brian Cox', 'Anthony Hopkins'], 'character': 'Hannibal Lecter', 'movies': ['Manhunter (1986)', 'The Silence of the Lambs (1991), Hannibal (2001), Red Dragon, (2002)'], 'type': 1}, 
    {'actors': ['Jeff Daniels', 'Derek Richardson'], 'character': 'Harry Dunne', 'movies': ['Dumb and Dumber (1994), Dumb and Dumber To (2014)', 'Dumb and Dumberer: When Harry Met Lloyd (2003)'], 'type': 1}, 
    {'actors': ['Matthew Broderick', 'French Stewart'], 'character': 'Inspector Gadget', 'movies': ['Inspector Gadget (1999)', 'Inspector Gadget 2 (2003)'], 'type': 1}, 
    {'actors': ['Chevy Chase', 'Jon Hamm'], 'character': 'Irwin \'Fletch\' Fletcher', 'movies': ['Fletch (1985), Fletch Lives (1989)', 'Confess Fletch (2022)'], 'type': 1}, 
    {'actors': ['Michael Caine', 'Sylvester Stallone'], 'character': 'Jack Carter', 'movies': ['Get Carter (1971)', 'Get Carter (2000)'], 'type': 1}, 
    {'actors': ['Harrison Ford', 'Chris Pine'], 'character': 'Jack Ryan', 'movies': ['Patriot Games (1992), Clear and Present Danger (1994)', 'Jack Ryan: Shadow Recruit (2014)'], 'type': 1}, 
    {'actors': ['Harrison Ford', 'Ben Affleck'], 'character': 'Jack Ryan', 'movies': ['Patriot Games (1992), Clear and Present Danger (1994)', 'The Sum of All Fears (2002)'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'Chris Pine'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October (1990)', 'Jack Ryan: Shadow Recruit (2014)'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'Harrison Ford'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October (1990)', 'Patriot Games (1992), Clear and Present Danger (1994)'], 'type': 1}, 
    {'actors': ['Alec Baldwin', 'Ben Affleck'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October (1990)', 'The Sum of All Fears (2002)'], 'type': 1}, 
    {'actors': ['Ben Affleck', 'Chris Pine'], 'character': 'Jack Ryan', 'movies': ['The Sum of All Fears (2002)', 'Jack Ryan: Shadow Recruit (2014)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['Dr. No (1962), From Russia with Love (1963), Goldfinger (1964), Thunderball (1965), You Only Live Twice (1967), Diamonds Are Forever (1971)', 'Casino Royale (2006), Quantum of Solace (2008), Skyfall (2012), Spectre (2015), No Time To Die (2021)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['Dr. No (1962), From Russia with Love (1963), Goldfinger (1964), Thunderball (1965), You Only Live Twice (1967), Diamonds Are Forever (1971)', 'GoldenEye (1995), Tomorrow Never Dies (1997), The World is Not Enough (1999), Die Another Day (2002)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Roger Moore'], 'character': 'James Bond', 'movies': ['Dr. No (1962), From Russia with Love (1963), Goldfinger (1964), Thunderball (1965), You Only Live Twice (1967), Diamonds Are Forever (1971)', 'Live and Let Die (1973), The Man with the Golden Gun (1974), The Spy Who Loved Me (1997), Moonraker (1979), For Your Eyes Only (1981), Octopussy (1983), A View to a Kill (1985)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'George Lazenby'], 'character': 'James Bond', 'movies': ['Dr. No (1962), From Russia with Love (1963), Goldfinger (1964), Thunderball (1965), You Only Live Twice (1967), Diamonds Are Forever (1971)', 'On Her Majesty\'s Secret Service (1969)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Timothy Dalton'], 'character': 'James Bond', 'movies': ['Dr. No (1962), From Russia with Love (1963), Goldfinger (1964), Thunderball (1965), You Only Live Twice (1967), Diamonds Are Forever (1971)', 'The Living Daylights (1987), Licence to Kill (1989)'], 'type': 1}, 
    {'actors': ['Pierce Brosnan', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['GoldenEye (1995), Tomorrow Never Dies (1997), The World is Not Enough (1999), Die Another Day (2002)', 'Casino Royale (2006), Quantum of Solace (2008), Skyfall (2012), Spectre (2015), No Time To Die (2021)'], 'type': 1}, 
    {'actors': ['Roger Moore', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['Live and Let Die (1973), The Man with the Golden Gun (1974), The Spy Who Loved Me (1997), Moonraker (1979), For Your Eyes Only (1981), Octopussy (1983), A View to a Kill (1985)', 'Casino Royale (2006), Quantum of Solace (2008), Skyfall (2012), Spectre (2015), No Time To Die (2021)'], 'type': 1}, 
    {'actors': ['Roger Moore', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['Live and Let Die (1973), The Man with the Golden Gun (1974), The Spy Who Loved Me (1997), Moonraker (1979), For Your Eyes Only (1981), Octopussy (1983), A View to a Kill (1985)', 'GoldenEye (1995), Tomorrow Never Dies (1997), The World is Not Enough (1999), Die Another Day (2002)'], 'type': 1}, 
    {'actors': ['Roger Moore', 'Timothy Dalton'], 'character': 'James Bond', 'movies': ['Live and Let Die (1973), The Man with the Golden Gun (1974), The Spy Who Loved Me (1997), Moonraker (1979), For Your Eyes Only (1981), Octopussy (1983), A View to a Kill (1985)', 'The Living Daylights (1987), Licence to Kill (1989)'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['On Her Majesty\'s Secret Service (1969)', 'Casino Royale (2006), Quantum of Solace (2008), Skyfall (2012), Spectre (2015), No Time To Die (2021)'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['On Her Majesty\'s Secret Service (1969)', 'GoldenEye (1995), Tomorrow Never Dies (1997), The World is Not Enough (1999), Die Another Day (2002)'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Roger Moore'], 'character': 'James Bond', 'movies': ['On Her Majesty\'s Secret Service (1969)', 'Live and Let Die (1973), The Man with the Golden Gun (1974), The Spy Who Loved Me (1997), Moonraker (1979), For Your Eyes Only (1981), Octopussy (1983), A View to a Kill (1985)'], 'type': 1}, 
    {'actors': ['George Lazenby', 'Timothy Dalton'], 'character': 'James Bond', 'movies': ['On Her Majesty\'s Secret Service (1969)', 'The Living Daylights (1987), Licence to Kill (1989)'], 'type': 1}, 
    {'actors': ['Timothy Dalton', 'Daniel Craig'], 'character': 'James Bond', 'movies': ['The Living Daylights (1987), Licence to Kill (1989)', 'Casino Royale (2006), Quantum of Solace (2008), Skyfall (2012), Spectre (2015), No Time To Die (2021)'], 'type': 1}, 
    {'actors': ['Timothy Dalton', 'Pierce Brosnan'], 'character': 'James Bond', 'movies': ['The Living Daylights (1987), Licence to Kill (1989)', 'GoldenEye (1995), Tomorrow Never Dies (1997), The World is Not Enough (1999), Die Another Day (2002)'], 'type': 1}, 
    {'actors': ['Jake Gyllenhaal', 'Patrick Swayze'], 'character': 'James Dalton', 'movies': ['Road House (1989)', 'Road House (2024)'], 'type': 1}, 
    {'actors': ['Tea Leoni', 'Jane Fonda'], 'character': 'Jane Harper', 'movies': ['Fun with Dick and Jane (2005)', 'Fun with Dick and Jane (1977)'], 'type': 1}, 
    {'actors': ['Andie MacDowell', 'Margot Robbie'], 'character': 'Jane Porter/Jane Clayton', 'movies': ['Greystoke: The Legend of Tarzan Lord of the Apes (1984)', 'The Legend of Tarzan (2016)'], 'type': 1}, 
    {'actors': ['Robert Redford', 'Leonardo DiCaprio'], 'character': 'Jay Gatsby', 'movies': ['The Great Gatsby (1974)', 'The Great Gatsby (2013)'], 'type': 1}, 
    {'actors': ['Patrick Swayze', 'Chris Hemsworth'], 'character': 'Jed Eckert', 'movies': ['Red Dawn (1984)', 'Red Dawn (2012)'], 'type': 1}, 
    {'actors': ['Elisabeth Shue', 'Claudia Wells'], 'character': 'Jennifer Parker', 'movies': ['Back to the Future II (1989), Back to the Future III (1990)', 'Back to the Future (1985)'], 'type': 1}, 
    {'actors': ['Colin Farrell', 'Chris Sarandon'], 'character': 'Jerry', 'movies': ['Fright Night (2011)', 'Fright Night (1985)'], 'type': 1}, 
    {'actors': ['Saoirse Ronan', 'Winona Ryder'], 'character': 'Jo March', 'movies': ['Little Woman (2019)', 'Little Women (1994)'], 'type': 1}, 
    {'actors': ['Nicole Kidman', 'Katharine Ross'], 'character': 'Joanna Eberhart', 'movies': ['The Stepford Wives (2004)', 'The Stepford Wives (1975)'], 'type': 1}, 
    {'actors': ['Joseph Gordon-Levitt', 'Bruce Willis'], 'character': 'Joe', 'movies': ['Looper (2012)'], 'type': 1}, 
    {'actors': ['Christopher Lambert', 'Alexander Skarsgård'], 'character': 'John Clayton/Tarzan', 'movies': ['Greystoke: The Legend of Tarzan Lord of the Apes (1984)', 'The Legend of Tarzan (2016)'], 'type': 1}, 
    {'actors': ['Edward Furlong', 'Nick Stahl'], 'character': 'John Connor', 'movies': ['Terminator 2: Judgment Day (1991), Terminator Dark Fate (2019)', 'Terminator 3: Rise of the Machines (2003)'], 'type': 1}, 
    {'actors': ['Edward Furlong', 'Jason Clarke'], 'character': 'John Connor', 'movies': ['Terminator 2: Judgment Day (1991), Terminator Dark Fate (2019)', 'Terminator Genisys (2015)'], 'type': 1}, 
    {'actors': ['Edward Furlong', 'Christian Bale'], 'character': 'John Connor', 'movies': ['Terminator 2: Judgment Day (1991), Terminator Dark Fate (2019)', 'Terminator Salvation (2009)'], 'type': 1}, 
    {'actors': ['Nick Stahl', 'Jason Clarke'], 'character': 'John Connor', 'movies': ['Terminator 3: Rise of the Machines (2003)', 'Terminator Genisys (2015)'], 'type': 1}, 
    {'actors': ['Nick Stahl', 'Christian Bale'], 'character': 'John Connor', 'movies': ['Terminator 3: Rise of the Machines (2003)', 'Terminator Salvation (2009)'], 'type': 1}, 
    {'actors': ['Christian Bale', 'Jason Clarke'], 'character': 'John Connor', 'movies': ['Terminator Salvation (2009)', 'Terminator Genisys (2015)'], 'type': 1}, 
    {'actors': ['Keanu Reeves', 'Luke Bracey'], 'character': 'Johnny Utah', 'movies': ['Point Break (1991)', 'Point Break (2015)'], 'type': 1}, 
    {'actors': ['John Lithgow', 'Fred Gwynne'], 'character': 'Jud', 'movies': ['Pet Sematary (2019)', 'Pet Sematary (1989)'], 'type': 1}, 
    {'actors': ['Sylvester Stallone', 'Karl Urban'], 'character': 'Judge Dredd', 'movies': ['Judge Dredd (1995)', 'Dredd (2012)'], 'type': 1}, 
    {'actors': ['Julia Stiles', 'Lee Remick'], 'character': 'Katherine Thorn', 'movies': ['The Omen (2006)', 'The Omen (1976)'], 'type': 1}, 
    {'actors': ['Margot Kidder', 'Melissa George'], 'character': 'Kathy Lutz', 'movies': ['The Amityville Horror (1979)', 'The Amityville Horror (2005)'], 'type': 1}, 
    {'actors': ['Michael Biehn', 'Anton Yelchin'], 'character': 'Kyle Reese', 'movies': ['The Terminator (1984)', 'Terminator Salvation (2009)'], 'type': 1}, 
    {'actors': ['Anton Yelchin', 'Jai Courtney'], 'character': 'Kyle Reese', 'movies': ['Terminator Salvation (2009)', 'Terminator Genisys (2015)'], 'type': 1}, 
    {'actors': ['Glen Campbell', 'Matt Damon'], 'character': 'LaBoeuf', 'movies': ['True Grit (1969)', 'True Grit (2010)'], 'type': 1}, 
    {'actors': ['Billy Dee Williams', 'Donald Glover'], 'character': 'Lando Calrissian ', 'movies': ['Star Wars: Episode V - The Empire Strikes Back (1980), Star Wars: Episode VI - Return of the Jedi (1983), Star War: Episode IX - The Rise of Skywalker (2019)', 'Solo: A Star Wars Story (2018)'], 'type': 1}, 
    {'actors': ['Angelina Jolie', 'Alicia Vikander'], 'character': 'Lara Croft', 'movies': ['Lara Croft: Tomb Raider (2001), Lara Croft: Tomb Raider - The Cradle of Life (2003)', 'Tomb Raider (2018)'], 'type': 1}, 
    {'actors': ['Timothee Chalamet', 'Christian Bale'], 'character': 'Laurie', 'movies': ['Little Woman (2019)', 'Little Women (1994)'], 'type': 1}, 
    {'actors': ['Matthew Broderick', 'Gene Wilder'], 'character': 'Leo Bloom', 'movies': ['The Producers (2005)', 'The Producers (1967)'], 'type': 1}, 
    {'actors': ['Tom Cruise', 'Sam Reid'], 'character': 'Lestat de Lioncourt', 'movies': ['Interview with the Vampire (1994)', 'Interview with the Vampire (TV) (2022)'], 'type': 1}, 
    {'actors': ['Tom Cruise', 'Stuart Townsend'], 'character': 'Lestat de Lioncourt', 'movies': ['Interview with the Vampire (1994)', 'Queen of the Damned (2002)'], 'type': 1}, 
    {'actors': ['Humphrey Bogart', 'Harrison Ford'], 'character': 'Linus Larrabee', 'movies': ['Sabrina (1954)', 'Sabrina (1995)'], 'type': 1}, 
    {'actors': ['Jim Carrey', 'Eric Christian Olsen'], 'character': 'Lloyd Christmas', 'movies': ['Dumb and Dumber (1994), Dumb and Dumber To (2014)', 'Dumb and Dumberer: When Harry Met Lloyd (2003)'], 'type': 1}, 
    {'actors': ['Sharon Stone', 'Kate Beckinsale'], 'character': 'Lori Quaid', 'movies': ['Total Recall (1990)', 'Total Recall (2012)'], 'type': 1}, 
    {'actors': ['Jason Clarke', 'Dale Midkiff'], 'character': 'Louis Creed', 'movies': ['Pet Sematary (2019)', 'Pet Sematary (1989)'], 'type': 1}, 
    {'actors': ['Rachel Zegler', 'Natalie Wood'], 'character': 'Maria', 'movies': ['West Side Story (2021)', 'West Side Story (1961)'], 'type': 1}, 
    {'actors': ['Julie Andrews', 'Emily Blunt'], 'character': 'Mary Poppins', 'movies': ['Mary Poppins (1964)', 'Mary Poppins Returns (2018)'], 'type': 1}, 
    {'actors': ['Nathan Lane', 'Zero Mostel'], 'character': 'Max Bialystock', 'movies': ['The Producers (2005)', 'The Producers (1967)'], 'type': 1}, 
    {'actors': ['Tom Hardy', 'Mel Gibson'], 'character': 'Max Rockatansky', 'movies': ['Mad Max: Fury Road (2015)', 'Mad Max (1979), Mad Max 2 (1981), Mad Max Beyond Thunderdome (1985)'], 'type': 1}, 
    {'actors': ['Emma Watson', 'Trini Alvarado'], 'character': 'Meg March', 'movies': ['Little Woman (2019)', 'Little Women (1994)'], 'type': 1}, 
    {'actors': ['Tim Reid', 'Isaiah Mustafa'], 'character': 'Mike Hanlon', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Tim Reid', 'Chosen Jacobs'], 'character': 'Mike Hanlon', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Chosen Jacobs', 'Isaiah Mustafa'], 'character': 'Mike Hanlon', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Christian Bale', 'Ben Kinglsey'], 'character': 'Moses', 'movies': ['Exodus: Gods and Kings (2014)', 'Moses (1995)'], 'type': 1}, 
    {'actors': ['Christian Bale', 'Val Kilmer'], 'character': 'Moses', 'movies': ['Exodus: Gods and Kings (2014)', 'The Prince of Egypt (1998)'], 'type': 1}, 
    {'actors': ['Val Kilmer', 'Ben Kinglsey'], 'character': 'Moses', 'movies': ['The Prince of Egypt (1998)', 'Moses (1995)'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Christian Bale'], 'character': 'Moses', 'movies': ['The Ten Commandments (1956)', 'Exodus: Gods and Kings (2014)'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Ben Kinglsey'], 'character': 'Moses', 'movies': ['The Ten Commandments (1956)', 'Moses (1995)'], 'type': 1}, 
    {'actors': ['Charlton Heston', 'Val Kilmer'], 'character': 'Moses', 'movies': ['The Ten Commandments (1956)', 'The Prince of Egypt (1998)'], 'type': 1}, 
    {'actors': ['Emma Roberts', 'Sophia Lillis'], 'character': 'Nancy Drew', 'movies': ['Nancy Drew (2007)', 'Nancy Drew and the Hiden Staircase (2019)'], 'type': 1}, 
    {'actors': ['Sam Waterston', 'Toby Maguire'], 'character': 'Nick Carraway', 'movies': ['The Great Gatsby (1974)', 'The Great Gatsby (2013)'], 'type': 1}, 
    {'actors': ['Tom Welling', 'Tom Atkins'], 'character': 'Nick Castle', 'movies': ['The Fog (2005)', 'The Fog (1980)'], 'type': 1}, 
    {'actors': ['Anthony Perkins', 'Vince Vaughn'], 'character': 'Norman Bates', 'movies': ['Psycho (1960), Psycho II (1983), Psycho III (1986), Psycho IV: The Beginning (1990)', 'Psycho (1998)'], 'type': 1}, 
    {'actors': ['Ewan McGregor', 'Alec Guiness'], 'character': 'Obi-Wan Kenobi', 'movies': ['Star Wars: Episode I - The Phantom Menace (1999), Star Wars: Episode II - Attack of the Clones (2002), Star Wars: Episode III – Revenge of the Sith (2005), Obi-Wan Kenobi (TV) (2022)', 'Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Star Wars: Episode VI - Return of the Jedi (1983)'], 'type': 1}, 
    {'actors': ['Timothée Chalamet', 'Kyle MacLachlan'], 'character': 'Paul Atreides', 'movies': ['Dune (2021), Dune Part Two (2024)', 'Dune (1984)'], 'type': 1}, 
    {'actors': ['Adamn Sandler', 'Burt Reynolds'], 'character': 'Paul Crewe', 'movies': ['The Longest Yard (2005)', 'The Longest Yard (1974)'], 'type': 1}, 
    {'actors': ['Tim Curry', 'Bill Skarsgård'], 'character': 'Pennywise', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Gerard Depardieu', 'Oliver Platt'], 'character': 'Porthos', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (1993)'], 'type': 1}, 
    {'actors': ['Gerard Depardieu', 'Ray Stevenson'], 'character': 'Porthos', 'movies': ['The Man in the Iron Mask (1998)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Oliver Platt', 'Ray Stevenson'], 'character': 'Porthos', 'movies': ['The Three Musketeers (1993)', 'The Three Musketeers (2011)'], 'type': 1}, 
    {'actors': ['Amy Seimetz', 'Denise Crosby'], 'character': 'Rachel Creed', 'movies': ['Pet Sematary (2019)', 'Pet Sematary (1989)'], 'type': 1}, 
    {'actors': ['Rachel McAdams', 'Reneé Rapp'], 'character': 'Regina George', 'movies': ['Mean Girls (2004)', 'Mean Girls (2024)'], 'type': 1}, 
    {'actors': ['Kevin Bacon', 'Kenny Wormald'], 'character': 'Ren', 'movies': ['Footloose (1984)', 'Footloose (2011)'], 'type': 1}, 
    {'actors': ['Harry Anderson', 'Bill Hader'], 'character': 'Richie Tozier', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Harry Anderson', 'Finn Wolfhard'], 'character': 'Richie Tozier', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Finn Wolfhard', 'Bill Hader'], 'character': 'Richie Tozier', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Liev Schreiber', 'Gregory Peck'], 'character': 'Robert Thorn', 'movies': ['The Omen (2006)', 'The Omen (1976)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Kevin Costner'], 'character': 'Robin Hood', 'movies': ['Robin and Marian (1976)', 'Robin Hood: Prince of Thieves (1991)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Russell Crowe'], 'character': 'Robin Hood', 'movies': ['Robin and Marian (1976)', 'Robin Hood (2010)'], 'type': 1}, 
    {'actors': ['Sean Connery', 'Taron Egerton'], 'character': 'Robin Hood', 'movies': ['Robin and Marian (1976)', 'Robin Hood (2018)'], 'type': 1}, 
    {'actors': ['Kevin Costner', 'Russell Crowe'], 'character': 'Robin Hood', 'movies': ['Robin Hood: Prince of Thieves (1991)', 'Robin Hood (2010)'], 'type': 1}, 
    {'actors': ['Kevin Costner', 'Taron Egerton'], 'character': 'Robin Hood', 'movies': ['Robin Hood: Prince of Thieves (1991)', 'Robin Hood (2018)'], 'type': 1}, 
    {'actors': ['Russell Crowe', 'Taron Egerton'], 'character': 'Robin Hood', 'movies': ['Robin Hood (2018)'], 'type': 1}, 
    {'actors': ['John Wayne', 'Jeff Bridges'], 'character': 'Rooster Cogburn', 'movies': ['True Grit (1969)', 'True Grit (2010)'], 'type': 1}, 
    {'actors': ['Johnny Galecki', 'Ethan Embry'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Christmas Vacation (1989)', 'National Lampoon\'s Vegas Vacation (1997)'], 'type': 1}, 
    {'actors': ['Johnny Galecki', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Christmas Vacation (1989)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Jason Lively', 'Johnny Galecki'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'National Lampoon\'s Christmas Vacation (1989)'], 'type': 1}, 
    {'actors': ['Jason Lively', 'Ethan Embry'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'National Lampoon\'s Vegas Vacation (1997)'], 'type': 1}, 
    {'actors': ['Jason Lively', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s European Vacation (1985)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Johnny Galecki'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'National Lampoon\'s Christmas Vacation (1989)'], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Jason Lively'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'National Lampoon\'s European Vacation (1985)'], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Ethan Embry'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'National Lampoon\'s Vegas Vacation (1997)'], 'type': 1}, 
    {'actors': ['Anthongy Michael Hall', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Vacation (1983)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Ethan Embry', 'Ed Helms'], 'character': 'Rusty Griswold', 'movies': ['National Lampoon\'s Vegas Vacation (1997)', 'Vacation (2015)'], 'type': 1}, 
    {'actors': ['Brad Pitt', 'Dean Martin'], 'character': 'Rusty Ryan', 'movies': ['Ocean\'s Eleven (2001)', 'Ocean\'s Eleven (1960)'], 'type': 1}, 
    {'actors': ['Audrey Hepburn', 'Julia Ormond'], 'character': 'Sabrina Fairchild', 'movies': ['Sabrina (1954)', 'Sabrina (1995)'], 'type': 1}, 
    {'actors': ['Kurt Russell', 'Tim Allen'], 'character': 'Santa Claus', 'movies': ['The Christmas Chronicles (2018), The Christmas Chronicles 2 (2020)', 'The Santa Clause (1994), The Santa Clause 2: The Mrs. Clause (2002), The Santa Clause 3: The Escape Clause (2006), The Santa Clauses (TV) (2022)'], 'type': 1}, 
    {'actors': ['Henry Cavill', 'Robert Downey Jr.'], 'character': 'Sherlock Homes', 'movies': ['Enola Holmes (2020), Enola Holmes 2 (2022)', 'Sherlock Holmes (2009), Sherlock Holmes: A Game of Shadows (2011)'], 'type': 1}, 
    {'actors': ['Kristen Stewart', 'Rachel Zegler'], 'character': 'Snow White', 'movies': ['Snow White and the Huntsman (2012)', 'Snow White (2025)'], 'type': 1}, 
    {'actors': ['Kristen Stewart', 'Lily Collins'], 'character': 'Snow White', 'movies': ['Snow White and the Huntsman (2012)', 'Mirror Mirror (2012)'], 'type': 1}, 
    {'actors': ['Rachel Zegler', 'Lily Collins'], 'character': 'Snow White', 'movies': ['Snow White (2025)', 'Mirror Mirror (2012)'], 'type': 1}, 
    {'actors': ['Richard Masur', 'Andy Bean'], 'character': 'Stanley Uris', 'movies': ['It (1990)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Richard Masur', 'Wyatt Oleff'], 'character': 'Stanley Uris', 'movies': ['It (1990)', 'It: Chater 1 (2017), It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Wyatt Oleff', 'Andy Bean'], 'character': 'Stanley Uris', 'movies': ['It: Chater 1 (2017), It: Chapter 2 (2019)', 'It: Chapter 2 (2019)'], 'type': 1}, 
    {'actors': ['Selma Blair', 'Adrienne Barbeau'], 'character': 'Stevie Wayne', 'movies': ['The Fog (2005)', 'The Fog (1980)'], 'type': 1}, 
    {'actors': ['James Franko', 'Jeff Goldblum'], 'character': 'The Wizard of Oz', 'movies': ['Oz the Great and Powerful (2013)', 'Wicked (2024)'], 'type': 1}, 
    {'actors': ['James Franko', 'Frank Morgan'], 'character': 'The Wizard of Oz', 'movies': ['Oz the Great and Powerful (2013)', 'The Wizard of Oz (1939)'], 'type': 1}, 
    {'actors': ['Frank Morgan', 'Jeff Goldblum'], 'character': 'The Wizard of Oz', 'movies': ['The Wizard of Oz (1939)', 'Wicked (2024)'], 'type': 1}, 
    {'actors': ['Steve McQueen', 'Pierce Brosnan'], 'character': 'Thomas Crown', 'movies': ['The Thomas Crown Affair (1968)', 'The Thomas Crown Affair (1999)'], 'type': 1}, 
    {'actors': ['Bruce Dern', 'Joel Edgerton'], 'character': 'Tom Buchanan', 'movies': ['The Great Gatsby (1974)', 'The Great Gatsby (2013)'], 'type': 1}, 
    {'actors': ['Ansel Elgort', 'Richard Beymer'], 'character': 'Tony', 'movies': ['West Side Story (2021)', 'West Side Story (1961)'], 'type': 1}, 
    {'actors': ['Rachelle Lefevre', 'Bryce Dallas Howard'], 'character': 'Victoria', 'movies': ['Twilight (2008)', 'The Twilight Saga: New Moon (2009)'], 'type': 1}, 
    {'actors': ['Robert De Niro', 'Marlon Brando'], 'character': 'Vito Corleone ', 'movies': ['The Godfather: Part II (1974)', 'The Godfather (1972)'], 'type': 1}, 
    {'actors': ['Ben Stiller', 'Danny Kaye'], 'character': 'Walter Mitty', 'movies': ['The Secret Life of Walter Mitty (2013)', 'The Secret Life of Walter Mitty (1947)'], 'type': 1}, 
    {'actors': ['Johnny Depp', 'Timothée Chalamet'], 'character': 'Willy Wonka', 'movies': ['Charlie and the Chocolate Factory (2005)', 'Wonka (2023)'], 'type': 1}, 
    {'actors': ['Gene Wilder', 'Johnny Depp'], 'character': 'Willy Wonka', 'movies': ['Willy Wonka and the Chocolate Factory (1971)', 'Charlie and the Chocolate Factory (2005)'], 'type': 1}, 
    {'actors': ['Gene Wilder', 'Timothée Chalamet'], 'character': 'Willy Wonka', 'movies': ['Willy Wonka and the Chocolate Factory (1971)', 'Wonka (2023)'], 'type': 1} 
];
