// Card Type 2 cards
export const cardDataType2 = [
    {'actors': ['Noah Ringer', 'Gordon Cormier'], 'character': 'Aang', 'movies': ['The Last Airbender (2010)', 'Avatar: The Last Air Bender (2024)'], 'type': 2}, 
    {'actors': ['Anne Hathaway', 'Barbara Feldon'], 'character': 'Agent 99', 'movies': ['Get Smart (2008)', 'Get Smart (TV) (1965)'], 'type': 2}, 
    {'actors': ['Angelina Jolie', 'Arielle Kebbel'], 'character': 'Amelia Sachs', 'movies': ['The Bone Collector (1999)', 'Lincoln Rhyme: Hunt for the Bone Collector (2020)'], 'type': 2}, 
    {'actors': ['Alexandra Daddario', 'Leah Sava\' Jeffries'], 'character': 'Annabeth', 'movies': ['Percy Jackson & the Lightning Theif (2010), Percy Jackson: Sea of Monsters (2013)', 'Percy Jackson and the Olympians (2023)'], 'type': 2}, 
    {'actors': ['Quinton \'Rampage\' Jackson', 'Mr. T'], 'character': 'B. A. Baracus', 'movies': ['The A-Team (2010)', 'The A-Team (TV) (1983)'], 'type': 2}, 
    {'actors': ['Johnny Depp', 'Jonathan Frid'], 'character': 'Barnabas Collins', 'movies': ['Dark Shadows (1966)', 'Dark Shadows (TV) (1967)'], 'type': 2}, 
    {'actors': ['RJ Cyler', 'David Yost'], 'character': 'Billy Cranston/Blue Ranger', 'movies': ['Power Rangers (2017)', 'Mighty Morphin Power Rangers (1993)'], 'type': 2}, 
    {'actors': ['Seann William Scott', 'John Schneider'], 'character': 'Bo Duke', 'movies': ['The Dukes of Hazzard (2005)', 'The Dukes of Hazzard (TV) (1979)'], 'type': 2}, 
    {'actors': ['Mark Wahlberg', 'Ryan Phillippe'], 'character': 'Bob Lee Swagger', 'movies': ['Shooter (2007)', 'Shooter (TV) (2016)'], 'type': 2}, 
    {'actors': ['Liam Neeson', 'Clive Standen'], 'character': 'Bryan Mills', 'movies': ['Taken (2008), Taken 2 (2012), Taken 3 (2014)', 'Taken (TV) (2017)'], 'type': 2}, 
    {'actors': ['John Candy', 'Mike Epps'], 'character': 'Buck Russell', 'movies': ['Uncle Buck (1989)', 'Uncle Buck (TV) (1990)'], 'type': 2}, 
    {'actors': ['Kristy Swanson', 'Sarah Michelle Gellar'], 'character': 'Buffy Anne Summers', 'movies': ['Buffy the Vampire Slayer (1992)', 'Buffy the Vampire Slayer (TV) (1997)'], 'type': 2}, 
    {'actors': ['Alicia Silverstone', 'Rachel Blanchard'], 'character': 'Cher Horowitz', 'movies': ['Clueless (1995)', 'Clueless (TV) (1996)'], 'type': 2}, 
    {'actors': ['Kelly Rohrbach', 'Pamela Anderson'], 'character': 'CJ Parker', 'movies': ['Baywatch (2017)', 'Baywatch (TV) (1989)'], 'type': 2}, 
    {'actors': ['Lilly Collins', 'Katherine McNamara'], 'character': 'Clary Fray', 'movies': ['The Mortal Instruments: City of Bones (2013)', 'Shadowhunters (TV) (2016)'], 'type': 2}, 
    {'actors': ['Ryan Gosling', 'Lee Majors'], 'character': 'Colt Seavers', 'movies': ['The Fall Guy (2024)', 'The Fall Guy (TV) (1981)'], 'type': 2}, 
    {'actors': ['Jessica Simpson', 'Catherine Bach'], 'character': 'Daisy Duke', 'movies': ['The Dukes of Hazzard (2005)', 'The Dukes of Hazzard (TV) (1979)'], 'type': 2}, 
    {'actors': ['Eliza Dushku', 'Annabella Didion'], 'character': 'Dana Tasker', 'movies': ['True Lies (1994)', 'True Lies (TV) (2023)'], 'type': 2}, 
    {'actors': ['Ben Stiller', 'Paul Michael Glaser'], 'character': 'David Starsky', 'movies': ['Starsky & Hutch (2004)', 'Starsky & Hutch (TV) (1975)'], 'type': 2}, 
    {'actors': ['Morgan Freeman', 'Tyler Perry'], 'character': 'Detective Alex Cross', 'movies': ['Along Came a Spider (2001), Kiss the Girls (1997)', 'Alex Cross (TV) (2024)'], 'type': 2}, 
    {'actors': ['Matt LeBlanc', 'Mark Goddard'], 'character': 'Don West', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['Matt LeBlanc', 'Ignacio Serricchio'], 'character': 'Don West', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (2018)'], 'type': 2}, 
    {'actors': ['Harrison Ford', 'Tim Daly'], 'character': 'Dr. Richard Kimble', 'movies': ['The Fugitive (1993)', 'The Fugitive (TV) (2000)'], 'type': 2}, 
    {'actors': ['Gary Oldman', 'Jonathan Harris'], 'character': 'Dr. Smith', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['Gerard Butler', 'Jonathan Rhys Meyers'], 'character': 'Dracula', 'movies': ['Dracula 2000 (2000)', 'Dracula (TV) (2013)'], 'type': 2}, 
    {'actors': ['Uma Thurman', 'Diana Rigg'], 'character': 'Emma Peel', 'movies': ['The Avengers (1998)', 'The Avengers (TV) (1961)'], 'type': 2}, 
    {'actors': ['Raul Julia', 'John Astin'], 'character': 'Gomez Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'The Addams Family (TV) (1964)'], 'type': 2}, 
    {'actors': ['Raul Julia', 'Luis Guzmán'], 'character': 'Gomez Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'Wednesday (2022)'], 'type': 2}, 
    {'actors': ['Arnold Schwarzenegger', 'Steve Howey'], 'character': 'Harry Tasker', 'movies': ['True Lies (1994)', 'True Lies (TV) (2023)'], 'type': 2}, 
    {'actors': ['Winston Duke', 'Avery Brooks'], 'character': 'Hawk', 'movies': ['Spenser Confidential (2020)', 'Spenser: For Hire (TV) (1985)'], 'type': 2}, 
    {'actors': ['Jamie Lee Curtis', 'Ginger Gonzaga'], 'character': 'Helen Tasker', 'movies': ['True Lies (1994)', 'True Lies (TV) (2023)'], 'type': 2}, 
    {'actors': ['Dwayne Johnson', 'Ryan Gosling'], 'character': 'Hercules', 'movies': ['Hercules (2014)', 'Young Hercules (TV) (1998)'], 'type': 2}, 
    {'actors': ['Kurt Russell', 'Richard Dean Anderson'], 'character': 'Jack O\'Neill', 'movies': ['Stargate (1994)', 'Stargate: SG-1 (TV) (1997)'], 'type': 2}, 
    {'actors': ['Tom Cruise', 'Alan Ritchson'], 'character': 'Jack Reacher', 'movies': ['Jack Reacher (2012), Jack Reacher: Never Go Back (2016)', 'Reacher (TV) (2022)'], 'type': 2}, 
    {'actors': ['Chris Pine', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['Jack Ryan: Shadow Recruit (2014)', 'Tom Clancy\'s Jack Ryan (TV) (2018)'], 'type': 2}, 
    {'actors': ['Harrison Ford', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['Patriot Games (1992), Clear and Present Danger (1994)', 'Tom Clancy\'s Jack Ryan (TV) (2018)'], 'type': 2}, 
    {'actors': ['Alec Baldwin', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['The Hunt for Red October (1990)', 'Tom Clancy\'s Jack Ryan (TV) (2018)'], 'type': 2}, 
    {'actors': ['Ben Affleck', 'John Krasinski'], 'character': 'Jack Ryan', 'movies': ['The Sum of All Fears (2002)', 'Tom Clancy\'s Jack Ryan (TV) (2018)'], 'type': 2}, 
    {'actors': ['Chris Tucker', 'Justin Hires'], 'character': 'James Carter', 'movies': ['Rush Hour (1998), Rush Hour 2 (2001), Rush Hour 3 (2007)', 'Rush Hour (TV) (2016)'], 'type': 2}, 
    {'actors': ['Dacre Montgomery', 'Austin St. John'], 'character': 'Jason Lee Scott/Red Ranger', 'movies': ['Power Rangers (2017)', 'Mighty Morphin Power Rangers (1993)'], 'type': 2}, 
    {'actors': ['Liam Neeson', 'George Peppard'], 'character': 'John "Hannibal" Smith', 'movies': ['The A-Team (2010)', 'The A-Team (TV) (1983)'], 'type': 2}, 
    {'actors': ['Armie Hammer', 'Clayton Moore'], 'character': 'John Reid/Lone Ranger', 'movies': ['The Lone Ranger (2013)', 'The Lone Ranger (TV) (1949)'], 'type': 2}, 
    {'actors': ['William Hurt', 'Guy Williams'], 'character': 'John Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['William Hurt', 'Toby Stephens'], 'character': 'John Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (2018)'], 'type': 2}, 
    {'actors': ['Ralph Fiennes', 'Patrick Macnee'], 'character': 'John Steed', 'movies': ['The Avengers (1998)', 'The Avengers (TV) (1961)'], 'type': 2}, 
    {'actors': ['Jackie Chan', 'Jon Foo'], 'character': 'Jonathan Lee', 'movies': ['Rush Hour (1998), Rush Hour 2 (2001), Rush Hour 3 (2007)', 'Rush Hour (TV) (2016)'], 'type': 2}, 
    {'actors': ['Heather Graham', 'Marta Kristen'], 'character': 'Judy Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['Heather Graham', 'Taylor Russell'], 'character': 'Judy Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (2018)'], 'type': 2}, 
    {'actors': ['Claire Danes', 'Peggy Lipton'], 'character': 'Julie Barnes', 'movies': ['The Mod Squad (1999)', 'The Mod Squad (TV) (1968)'], 'type': 2}, 
    {'actors': ['Nicola Peltz Beckham', 'Kiawentiio'], 'character': 'Katara', 'movies': ['The Last Airbender (2010)', 'Avatar: The Last Air Bender (2024)'], 'type': 2}, 
    {'actors': ['Owen Wilson', 'David Soul'], 'character': 'Ken Hutchinson', 'movies': ['Starsky & Hutch (2004)', 'Starsky & Hutch (TV) (1975)'], 'type': 2}, 
    {'actors': ['Naomi Scott', 'Amy Jo Johnson'], 'character': 'Kimberley Hart/Pink Ranger', 'movies': ['Power Rangers (2017)', 'Mighty Morphin Power Rangers (1993)'], 'type': 2}, 
    {'actors': ['Stuart Townsend', 'Sam Reid'], 'character': 'Lestat de Lioncourt', 'movies': ['Queen of the Damned (2002)', 'Interview with the Vampire (TV) (2022)'], 'type': 2}, 
    {'actors': ['Omar Epps', 'Clarence Williams III'], 'character': 'Linc Hayes', 'movies': ['The Mod Squad (1999)', 'The Mod Squad (TV) (1968)'], 'type': 2}, 
    {'actors': ['Denzel Washington', 'Russell Hornsby'], 'character': 'Lincoln Rhyme', 'movies': ['The Bone Collector (1999)', 'Lincoln Rhyme: Hunt for the Bone Collector (2020)'], 'type': 2}, 
    {'actors': ['Lucy Fry', 'Daniela Nieves'], 'character': 'Lissa Dragomir', 'movies': ['Vampire Academy (2014)', 'Vampire Acdemy (TV) (2022)'], 'type': 2}, 
    {'actors': ['Johnny Knoxville', 'Tom Wopat'], 'character': 'Luke Duke', 'movies': ['The Dukes of Hazzard (2005)', 'The Dukes of Hazzard (TV) (1979)'], 'type': 2}, 
    {'actors': ['Mel Gibson', 'Clayne Crawford'], 'character': 'Martin Riggs', 'movies': ['Leathal Weapon (1987), Leathal Weapon 2 (1989), Leathal Weapon 3 (1992), Leathal Weapon 4 (1998)', 'Leathal Weapon (TV) (2016)'], 'type': 2}, 
    {'actors': ['Zac Efron', 'David Charvet'], 'character': 'Matt Brody', 'movies': ['Baywatch (2017)', 'Baywatch (TV) (1989)'], 'type': 2}, 
    {'actors': ['Mimi Rogers', 'Jane Lockhart'], 'character': 'Maureen Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['Mimi Rogers', 'Molly Parker'], 'character': 'Maureen Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (2018)'], 'type': 2}, 
    {'actors': ['Steve Carell', 'Don Adams'], 'character': 'Maxwell Smart', 'movies': ['Get Smart (2008)', 'Get Smart (TV) (1965)'], 'type': 2}, 
    {'actors': ['Matthew McConaughey', 'Manuel Garcia-Fulfo'], 'character': 'Mick Haller', 'movies': ['The Lincoln Lawyer (2011)', 'The Lincoln Lawyer (TV) (2022)'], 'type': 2}, 
    {'actors': ['Macaulay Culkin', 'Sayeed Shahidi'], 'character': 'Miles Russell', 'movies': ['Uncle Buck (1989)', 'Uncle Buck (TV) (1990)'], 'type': 2}, 
    {'actors': ['Dwayne Johnson', 'David Hasselhoff'], 'character': 'Mitch Buchannon', 'movies': ['Baywatch (2017)', 'Baywatch (TV) (1989)'], 'type': 2}, 
    {'actors': ['Anjelica Huston', 'Carolyn Jones'], 'character': 'Morticia Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'The Addams Family (TV) (1964)'], 'type': 2}, 
    {'actors': ['Anjelica Huston', 'Catherine Zeta-Jones'], 'character': 'Morticia Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'Wednesday (2022)'], 'type': 2}, 
    {'actors': ['Sharlto Copley', 'Dwight Schultz'], 'character': 'Murdock', 'movies': ['The A-Team (2010)', 'The A-Team (TV) (1983)'], 'type': 2}, 
    {'actors': ['Emma Roberts', 'Kennedy McMann'], 'character': 'Nancy Drew', 'movies': ['Nancy Drew (2007)', 'Nancy Drew (TV) (2019)'], 'type': 2}, 
    {'actors': ['Sophia Lillis', 'Kennedy McMann'], 'character': 'Nancy Drew', 'movies': ['Nancy Drew and the Hiden Staircase (2019)', 'Nancy Drew (TV) (2019)'], 'type': 2}, 
    {'actors': ['Anne Parillaud', 'Maggie Q'], 'character': 'Nikita', 'movies': ['La Femme Nikita (1990)', 'Nikita (TV) (2010)'], 'type': 2}, 
    {'actors': ['Anne Parillaud', 'Peta Wilson'], 'character': 'Nikita', 'movies': ['La Femme Nikita (1990)', 'La Femme Nikita (TV) (1997)'], 'type': 2}, 
    {'actors': ['Anthony Perkins', 'Freddie Highmore'], 'character': 'Norman Bates', 'movies': ['Psycho (1960), Psycho II (1983), Psycho III (1986), Psycho IV: The Beginning (1990)', 'Bates Motel (2013)'], 'type': 2}, 
    {'actors': ['Lacey Chabert', 'Angela Cartwright'], 'character': 'Penny Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['Lacey Chabert', 'Mina Sundwall'], 'character': 'Penny Robinson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (2018)'], 'type': 2}, 
    {'actors': ['Logal Lerman', 'Walker Scobell'], 'character': 'Percy Jackson', 'movies': ['Percy Jackson & the Lightning Theif (2010), Percy Jackson: Sea of Monsters (2013)', 'Percy Jackson and the Olympians (2023)'], 'type': 2}, 
    {'actors': ['Giovanni Ribisi', 'Michael Cole'], 'character': 'Pete Cochran', 'movies': ['The Mod Squad (1999)', 'The Mod Squad (TV) (1968)'], 'type': 2}, 
    {'actors': ['Dev Patel', 'Dallas Liu'], 'character': 'Prince Zuko', 'movies': ['The Last Airbender (2010)', 'Avatar: The Last Air Bender (2024)'], 'type': 2}, 
    {'actors': ['Jimmy Workman', 'Isaac Ordonez'], 'character': 'Pugsley Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'The Addams Family (TV) (1964)'], 'type': 2}, 
    {'actors': ['Jimmy Workmann', 'Ken Weatherwax'], 'character': 'Pugsley Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'Wednesday (2022)'], 'type': 2}, 
    {'actors': ['Denzel Washington', 'Edward Woodward'], 'character': 'Robert McCall', 'movies': ['The Equalizer (2014), The Equalizer 2 (2018), The Equalizer 3 (2023)', 'The Equalizer (1985)'], 'type': 2}, 
    {'actors': ['Danny Glover', 'Damon Wayans'], 'character': 'Roger Murtaugh', 'movies': ['Leathal Weapon (1987), Leathal Weapon 2 (1989), Leathal Weapon 3 (1992), Leathal Weapon 4 (1998)', 'Leathal Weapon (TV) (2016)'], 'type': 2}, 
    {'actors': ['Zoey Deutch', 'Sisi Stringer'], 'character': 'Rose Hathaway', 'movies': ['Vampire Academy (2014)', 'Vampire Acdemy (TV) (2022)'], 'type': 2}, 
    {'actors': ['Emilia Clarke', 'Lena Headey'], 'character': 'Sarah Connor', 'movies': ['Terminator Genisis (2015)', 'Terminator: The Sarah Connor Chronicles (2008)'], 'type': 2}, 
    {'actors': ['Linda Hamilton', 'Lena Headey'], 'character': 'Sarah Connor', 'movies': ['The Terminator (1984), Terminator 2: Judgment Day (1991), Terminator: Dark Fate (2019)', 'Terminator: The Sarah Connor Chronicles (2008)'], 'type': 2}, 
    {'actors': ['Val Kilmer', 'Roger Moore'], 'character': 'Simon Templar', 'movies': ['The Saint (1997)', 'The Saint (TV) (1962)'], 'type': 2}, 
    {'actors': ['Mark Wahlberg', 'Robert Urich'], 'character': 'Spenser', 'movies': ['Spenser Confidential (2020)', 'Spenser: For Hire (TV) (1985)'], 'type': 2}, 
    {'actors': ['Alexandra Daddario', 'Nicole Eggert'], 'character': 'Summer Quinn', 'movies': ['Baywatch (2017)', 'Baywatch (TV) (1989)'], 'type': 2}, 
    {'actors': ['Bradley Cooper', 'Dirk Benedict'], 'character': 'Templeton \'Faceman\' Peck', 'movies': ['The A-Team (2010)', 'The A-Team (TV) (1983)'], 'type': 2}, 
    {'actors': ['Bruce Willis', 'Eddie Redmayne'], 'character': 'The Jackal', 'movies': ['The Jackal (1997)', 'The Day of the Jackal (2024)'], 'type': 2}, 
    {'actors': ['Jean Louisa Kelly', 'Iman Benson'], 'character': 'Tia Russell', 'movies': ['Uncle Buck (1989)', 'Uncle Buck (TV) (1990)'], 'type': 2}, 
    {'actors': ['Jonny Depp', 'Jay Silverheels'], 'character': 'Tonto', 'movies': ['The Lone Ranger (2013)', 'The Lone Ranger (TV) (1949)'], 'type': 2}, 
    {'actors': ['Becky G', 'Thuy Trang'], 'character': 'Trini Kwan/Yellow Ranger', 'movies': ['Power Rangers (2017)', 'Mighty Morphin Power Rangers (1993)'], 'type': 2}, 
    {'actors': ['Christopher Lloyd', 'Jackie Coogan'], 'character': 'Uncle Fester Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'The Addams Family (TV) (1964)'], 'type': 2}, 
    {'actors': ['Christopher Lloyd', 'Fred Armisen'], 'character': 'Uncle Fester Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'Wednesday (2022)'], 'type': 2}, 
    {'actors': ['Emily Browning', 'Malina Weissman'], 'character': 'Violet Baudelaire', 'movies': ['A Series of Unfortunate Events (2004)', 'A Series of Unfortunate Events (TV) (2017)'], 'type': 2}, 
    {'actors': ['Christina Ricci', 'Lisa Loring'], 'character': 'Wednesday Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'The Addams Family (TV) (1964)'], 'type': 2}, 
    {'actors': ['Christina Ricci', 'Jenna Ortega'], 'character': 'Wednesday Addams', 'movies': ['The Addams Family (1991), The Addams Family Values (1993)', 'Wednesday (2022)'], 'type': 2}, 
    {'actors': ['Jack Johnson', 'Bill Mumy'], 'character': 'Will Robionson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (1965)'], 'type': 2}, 
    {'actors': ['Jack Johnson', 'Maxwell Jenkins'], 'character': 'Will Robionson', 'movies': ['Lost In Space (1998)', 'Lost in Space (TV) (2018)'], 'type': 2}, 
    {'actors': ['Ludi Lin', 'Walter Emanuel Jones'], 'character': 'Zack Taylor/Black Ranger', 'movies': ['Power Rangers (2017)', 'Mighty Morphin Power Rangers (1993)'], 'type': 2}, 
    {'actors': ['Saoirse Ronan', 'Esme Creed-Miles'], 'character': 'Hanna', 'movies': ['Hanna (2011)', 'Hanna (TV) (2019)'], 'type': 2}, 
    {'actors': ['Dax Shepard', 'Larry Wilcox'], 'character': 'Jon', 'movies': ['CHiPS (2017)', 'CHiPS (TV) (1977)'], 'type': 2}, 
    {'actors': ['Michael Pena', 'Erik Estrada'], 'character': 'Ponch', 'movies': ['CHiPS (2017)', 'CHiPS (TV) (1977)'], 'type': 2}, 
    {'actors': ['Will Smith', 'Robert Conrad'], 'character': 'James West', 'movies': ['Wild Wild West (1999)', 'The Wild Wild West (TV) (1965)'], 'type': 2}, 
    {'actors': ['Kevin Kline', 'Ross Martin'], 'character': 'Artemus Gordon', 'movies': ['Wild Wild West (1999)', 'The Wild Wild West (TV) (1965)'], 'type': 2} 
];
